var $jscomp$destructuring$var0=kontra,init=$jscomp$destructuring$var0.init,Sprite=$jscomp$destructuring$var0.Sprite,GameLoop=$jscomp$destructuring$var0.GameLoop,load=$jscomp$destructuring$var0.load,setImagePath=$jscomp$destructuring$var0.setImagePath,imageAssets=$jscomp$destructuring$var0.imageAssets,SpriteSheet=$jscomp$destructuring$var0.SpriteSheet,initPointer=$jscomp$destructuring$var0.initPointer,onPointerDown=$jscomp$destructuring$var0.onPointerDown,$jscomp$destructuring$var1=init(),canvas=$jscomp$destructuring$var1.canvas;
initPointer();function jump(){var b=["C6 e"],g="undefined"!==typeof AudioContext?new AudioContext:new webkitAudioContext;b=new TinyMusic.Sequence(g,120,b);b.loop=!1;b.smoothing=.1;b.play()}
function ost(b){var g="C5 h;D5 q;E5 q;D5 q;C5 q;B4 q;C5 q;D5 h;E5 q;D5 q;E5 q;F5 q;E5 e;D5 e".split(";"),d="-   e;D5  e;E5  e;D5  e;Cb4 e;C5  e;B4  e;Gb4 e;D4  e;C4  e;Fb4 e;E4  e;G4  e;F4  e;E4  q;-   e;D5  e;E5  e;D5  e;Cb4 e;C5  e;B4  e;Gb4 e;D4  e;C4  e;Fb4 e;E4  e;G4  e;F4  e;E4  q".split(";");"game"==b?(b="undefined"!==typeof AudioContext?new AudioContext:new webkitAudioContext,sequence1=new TinyMusic.Sequence(b,120,g),sequence1.loop=!0,sequence1.smoothing=.1,sequence1.play()):"end"==b&&(sequence1.stop(),
b="undefined"!==typeof AudioContext?new AudioContext:new webkitAudioContext,d=new TinyMusic.Sequence(b,120,d),d.loop=!0,d.smoothing=.1,d.play())}var start=!1,points=0,hits=3,grav={force:.3,velocity:0};function gravity(b){b.y<canvas.height-16&&b.y+grav.velocity<canvas.height-16?(grav.velocity+=grav.force,b.y+=grav.velocity):b.y+grav.velocity>=canvas.height-16&&(b.y=canvas.height-16)}
function gameOver(){draw("Game Over",4,"red",50,100);draw("Points "+points.toString(),4,"red",65,150);draw("Click to try again",2,"black",55,200)}function end(){draw("A game made",1.5,"purple",10,10);draw("by jAlvarez",1.5,"purple",15,20)}function begin(){draw("Meadow",4,"yellow",70,100);draw("click to start",2,"orange",75,220)}setImagePath("./img");
load("back.png","gBack.png","mBack.png","floorAnim.png","gFloorAnim.png","mFloorAnim.png","bunAnim.png","batAnim.png","beastAnim.png","heartAnim.png","empAnim.png","oScene.png","eScene.png").then(function(b){b=SpriteSheet({image:imageAssets.batAnim,frameWidth:8,frameHeight:8,animations:{fly:{frames:"0..1",frameRate:5}}});var g=SpriteSheet({image:imageAssets.beastAnim,frameWidth:8,frameHeight:8,animations:{stomp:{frames:"0..1",frameRate:5}}}),d=[Sprite({x:10,y:Math.floor(Math.random()*(canvas.height-
50))+16,dx:2,width:16,height:16,anchor:{x:.5,y:.5},animations:b.animations}),Sprite({x:30,y:Math.floor(Math.random()*(canvas.height-50))+16,dx:2.5,width:16,height:16,anchor:{x:.5,y:.5},animations:b.animations}),Sprite({x:10,y:canvas.height-24,dx:1,width:16,height:16,anchor:{x:.5,y:.5},animations:g.animations})],e=Sprite({x:0,y:0,width:canvas.width,height:canvas.height,image:imageAssets.back});b=SpriteSheet({image:imageAssets.bunAnim,frameWidth:8,frameHeight:8,animations:{walk:{frames:"0..1",frameRate:5}}});
var c=Sprite({x:canvas.width,y:canvas.height-16,width:16,height:16,anchor:{x:1,y:1},animations:b.animations}),n=SpriteSheet({image:imageAssets.mFloorAnim,frameWidth:8,frameHeight:8,animations:{walk:{frames:"0..1",frameRate:3}}}),p=SpriteSheet({image:imageAssets.gFloorAnim,frameWidth:8,frameHeight:8,animations:{walk:{frames:"0..1",frameRate:3}}}),k=SpriteSheet({image:imageAssets.floorAnim,frameWidth:8,frameHeight:8,animations:{walk:{frames:"0..1",frameRate:3}}}),f=[Sprite({x:0,y:canvas.height,width:canvas.width/
3,height:16,anchor:{x:0,y:1},animations:k.animations}),Sprite({x:canvas.width/3,y:canvas.height,width:canvas.width/3,height:16,anchor:{x:0,y:1},animations:k.animations}),Sprite({x:2*canvas.width/3,y:canvas.height,width:canvas.width/3,height:16,anchor:{x:0,y:1},animations:k.animations})],l=SpriteSheet({image:imageAssets.heartAnim,frameWidth:8,frameHeight:8,animations:{glint:{frames:"0..1",frameRate:3}}}),q=SpriteSheet({image:imageAssets.empAnim,frameWidth:8,frameHeight:8,animations:{glint:{frames:"0..1",
frameRate:3}}}),h=[Sprite({x:10,y:5,width:16,height:16,anchor:{x:0,y:0},animations:l.animations}),Sprite({x:34,y:5,width:16,height:16,anchor:{x:0,y:0},animations:l.animations}),Sprite({x:58,y:5,width:16,height:16,anchor:{x:0,y:0},animations:l.animations})],m=GameLoop({update:function(){start?(h.forEach(function(a){a.update()}),e.update(),f.forEach(function(a){a.update()}),d.forEach(function(a){a.update();a.x>canvas.width&&(a.x=-20,a.animations.fly&&(a.y=Math.floor(Math.random()*(canvas.height-50))+
16),points++,10==points&&-19>a.x?(e.image=imageAssets.gBack,f.forEach(function(a){a.animations=p.animations})):20==points&&-19>a.x?(e.image=imageAssets.mBack,f.forEach(function(a){a.animations=n.animations})):30==points&&-19>a.x&&(e.image=imageAssets.eScene,end(),c.width=0,d.forEach(function(a){a.width=0;a.dx=0}),f.forEach(function(a){a.width=0;a.height=0}),h.forEach(function(a){a.width=0;a.height=0})),console.log("points",points));a.x-a.width/2<c.x&&a.x+a.width/2>c.x-c.width&&a.y-a.height/2<c.y&&
a.y+a.height/2>c.y-c.height&&(h[hits-1].animations=q.animations,--hits,a.x=-20,a.animations.fly?a.y=Math.floor(Math.random()*(canvas.height-50))+16:a.dx=Math.floor(1.5*Math.random())+1)}),c.update(),gravity(c)):(e.image=imageAssets.oScene,begin());onPointerDown(function(a,b){start||(start=!0,e.image=imageAssets.back,ost("game"));0===hits&&(hits=3,points=0,e.image=imageAssets.back,f.forEach(function(a){a.animations=k.animations}),m.start(),h.forEach(function(a){a.animations=l.animations}));c.y-grav.velocity>
canvas.height-50&&(grav.velocity=-8,c.y+=grav.velocity,jump())})},render:function(){start?(e.render(),f.forEach(function(a){a.render()}),d.forEach(function(a){a.render()}),c.render(),h.forEach(function(a){a.render()}),0===hits?(m.stop(),d.forEach(function(a){a.x=-20}),gameOver()):30==points&&(end(),ost("end"),m.stop())):(e.render(),begin())}});m.start()})["catch"](function(b){});
