var t="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;function v(){t.Symbol||(t.Symbol=x);v=function(){}}var y=0;function x(h){return"jscomp_symbol_"+h+y++}function z(){v();t.Symbol.iterator||(t.Symbol.iterator=t.Symbol("iterator"));z=function(){}}
function B(h){z();if(h[t.Symbol.iterator])return h[t.Symbol.iterator]();if(!(h instanceof Array||"string"==typeof h||h instanceof String))throw new TypeError(h+" is not iterable");var c=0;return{next:function(){return c==h.length?{done:!0}:{done:!1,value:h[c++]}}}}function C(h){if(!(h instanceof Array)){h=B(h);for(var c,e=[];!(c=h.next()).done;)e.push(c.value);h=e}return h}
this.glitchSquad=function(h){function c(b){if(e[b])return e[b].J;var f=e[b]={J:{},id:b,loaded:!1};h[b].call(f.J,f,f.J,c);f.loaded=!0;return f.J}var e={};c.o=h;c.h=e;c.j="/";return c(0)}([function(h,c,e){c=e(1);var b=e(18);e(24);e={};e.client=b.start;e.server=c.Ea;h.J=e},function(h,c,e){function b(a,b){var k=p.U();k.local=!1;new d.va(a,b,k,n,g)}function f(g){var d=q.find(function(a){return!a.L&&a!==g&&a.waiting});d?b(g,d):g.l.emit("state",a.Qa())}var d=e(2),a=e(4);h=e(3);var k=e(10),l=e(11),m=e(16),
p=e(17),n=h.ia([m.ka,l.ea]),g=h.ha([k.da]),q=[];c.start=b;c.Ea=function(g){var d={l:g,waiting:!1};q.push(d);g.on("waiting",function(){d.waiting=!0;f(d)});g.on("disconnect",function(){q.splice(q.indexOf(d),1);if(d.L){var g=d.L;g.T.end();g.waiting=!0;g.l.emit("state",a.Ra())}})}},function(h,c,e){function b(d,a,b,e,c){this.h=d;this.j=a;this.state=b;this.B=e;this.I=c;this.C=[];this.o=this.o.bind(this);this.s=this.s.bind(this);this.B=this.B.bind(this);this.I=this.I.bind(this);this.Pa();this.W=f.H(b);this.C=
[];this.o({f:0,active:0,b:0,a:{}})}var f=e(3);b.prototype.end=function(){this.h?this.P(this.h):"";this.j?this.P(this.j):"";this.j=this.h=void 0};b.prototype.o=function(d){if(10===d.f||4<this.C.length&&.985<Math.random())return this.s(f.H(this.W),[].concat(C(this.C)));var a=this.B(this.state,d);this.Ma(d);this.I(a.g.find(function(a){return a.a&&10===a.a.f})?a.g.filter(function(a){return a.a&&10===a.a.f}):a.g,this.o);a.g=[];this.state=a;this.K(a);11===d.f?this.la():""};b.prototype.la=function(){this.h.waiting=
!1;this.j.waiting=!1;this.end()};b.prototype.Pa=function(){var d=this;this.h.ba=0;this.j.ba=1;this.h.L=this.j;this.j.L=this.h;this.h.T=this;this.j.T=this;this.h.l.on("action",function(a){return 0===a.b?d.o(a):""});this.j.l.on("action",function(a){return 1===a.b?d.o(a):""});this.h.l.on("disconnect",function(){return d.end()});this.j.l.on("disconnect",function(){return d.end()})};b.prototype.P=function(d){d&&(d.l?d.l.removeAllListeners("action"):"",d.L=void 0,d.T=void 0,d.ba=void 0)};b.prototype.K=
function(d){var a=f.H(d);d=f.H(d);a.O=0;d.O=1;this.h?this.h.l.emit("state",a):"";this.j?this.j.l.emit("state",d):""};b.prototype.Ma=function(d){11!==d.f?this.C.push(d):""};b.prototype.s=function(d,a){var b=a.shift();d.active=b.active;if(0<a.length){var e=this;d.s=!0;var c=this.B(d,b);c.g=[];this.K(c);setTimeout(function(){return e.s(c,a)},140)}else{d.s=!1;var f=this.B(d,b);f.g&&0<f.g.length&&(f.g=f.g.filter(function(a){return a.a?10!==a.a.f:!0}),f.g=f.g.find(function(a){return a.a&&11===a.a.f})?[f.g.find(function(a){return a.a&&
11===a.a.f})]:f.g);this.I(f.g,this.o);this.state=f;this.K(f);11===b.f?this.la():""}};c.va=b},function(h,c){function e(b){return JSON.parse(JSON.stringify(b))}c.Ga=function(b,c){return function(d){var a=b.reduce(function(a,b){return a+b(d)},"");c.innerHTML=a}};c.D=function(b,c){b.forEach(function(d){var a=document.getElementById(d.id);a?a[d.event]=function(){return c(d.action)}:""})};c.ha=function(b){return function(c,d){c.forEach(function(a){return b.forEach(function(b){return b(a,d)})})}};c.ia=function(b){return function(c,
d){return b.reduce(function(a,b){return b(a,d)},e(c))}};c.H=e},function(h,c,e){function b(a){return{location:0,local:!1,i:f.qa(a.map(function(a,b){return d.pa(b,a)})),m:[],g:[],c:[],ga:!1}}var f=e(5),d=e(9),a="#GLITCH##  ;###SQUAD#;Waiting ;forONLINE;#OPONNENT;#online##".split(";"),k="#OPONNENT#;###LEFT### ;Waitingfor;## ONLINE#;#OPONNENT#;GLITCHSQDD".split(";");c.Qa=function(){return b(a)};c.Ra=function(){return b(k)}},function(h,c,e){function b(b){function c(e,n,g){n.v=n.v.map(function(c,k){var f;
a:{if(3!==c&&0!==n.type&&4!==n.type){var m=d.fa(g,e,k);f=m.x;m=m.y;if(0>m||0>f||a.size[0]-1<m||a.size[1]-1<f){f=.2<Math.random()?3:c;break a}if(!b[m]||!b[m][f]){f=c;break a}f=b[m][f];if(0===f.type||3===f.v[(k+3)%6]){f=.1<Math.random()?3:c;break a}}f=c}return f});return n}return b.map(function(a,b){return a.map(function(a,d){return c(b,a,d)})})}var f=e(6),d=e(7),a=e(8),k=[[[1,a.size[1]/2-1],[a.size[0]-1,1],[a.size[0]-2,a.size[1]-2]],[[a.size[0]-1,a.size[1]/2-1],[1,1],[1,a.size[1]-3]],[[a.size[0]/2-
1,1],[1,a.size[1]-2],[a.size[0]-2,a.size[1]-2]],[[a.size[0]/2-1,a.size[1]-1],[1,1],[a.size[0]-2,1]]];c.Ha=function(){return b(function(a){var b=k[Math.floor(Math.random()*k.length)],d=.5<Math.random(),c=b[0],g=b[d?1:2],b=b[d?2:1];a[c[0]][c[1]]=f.Aa(c[1],c[0]);a[g[0]][g[1]]=f.ca(g[1],g[0],0);a[b[0]][b[1]]=f.ca(b[1],b[0],1);return a}(function(){function b(d){return Array.from(Array(a.size[1]),function(a,b){return f.La(b,d)})}return Array.from(Array(a.size[0]),function(a,d){return b(d)})}()))};c.qa=
b},function(h,c){function e(b,a){return{x:b,y:a,v:f(),c:[],G:[],type:.85<Math.random()?0:1}}function b(b){return Array.from(Array(6),function(){return b})}function f(){return Array.from(Array(6),function(){return.6<Math.random()?0:.8<Math.random()?1:Math.floor(4*Math.random())})}c.Sa=e;c.La=function(b,a){return e(b,a)};c.Oa=function(b,a,c){b=e(b,a);b.char=c;b.type="#"===c?0:2;return b};c.ca=function(c,a,f){c=e(c,a);c.type=3;c.b=f;c.v=b(1);return c};c.Aa=function(c,a){var f=e(c,a);f.type=4;f.v=b(2);
return f}},function(h,c,e){function b(a,g,b){var d=B(c.ya[g%2][b]);b=d.next().value;d=d.next().value;return{x:b+a,y:d+g}}function f(a,g){return-1<a&&a<p.size[1]&&-1<g&&g<p.size[0]}function d(a,g,b){return 0!==b[g][a].type}function a(a,g,c,d){var e=b(a,g,c);a=d[g][a].v[c];c=d[e.y][e.x].v[(c+3)%6];return a>c?a:c}function k(c,g,e,k,m){var l=b(c,g,e);return f(l.x,l.y)&&d(l.x,l.y,k)&&a(c,g,e,k)<=m}function l(c,g,e,k,l){var m=b(c,g,e);return f(m.x,m.y)&&d(m.x,m.y,k)&&a(c,g,e,k)===l}function m(a,g,c,e,k,
l,h){l=void 0===l?[]:l;h=void 0===h?1:h;var w={x:a,y:g,d:c,type:e[g][a].v[c]};a=h%2?b(a,g,c):w;return f(a.x,a.y)&&d(a.x,a.y,e)&&w.type<k?m(a.x,a.y,(c+3)%6,e,k,l.concat([w]),h+1):l}var p=e(8);c.ya=[[[1,0],[0,1],[-1,1],[-1,0],[-1,-1],[0,-1]],[[1,0],[1,1],[0,1],[-1,0],[0,-1],[1,-1]]];c.Za=function(){return!0};c.fa=b;c.wa=function(a,b,c,d){return k(a,b,c,d,1)};c.Ya=d;c.Wa=function(a,b,c,d){return k(a,b,c,d,1)};c.Xa=function(a,b,c,d){return k(a,b,c,d,3)};c.Va=a;c.Ua=k;c.Ta=l;c.xa=function(a,c,d,e){var f=
b(a,c,d);if(!l(a,c,d,e,2))return!1;a=2===e[c][a].v[d]?{x:a,y:c,d:d}:{x:f.x,y:f.y,d:(d+3)%6};return{Ba:f.x,Ca:f.y,ra:a.x,sa:a.y,oa:a.d}};c.aa=m},function(h,c){c.size=[8,10]},function(h,c,e){function b(a,b){return b.map(function(a){return a.code+"#"+a.name}).concat(["P"+(a+1)+"#HOTSEAT","#ONLINE###"]).map(function(a,b){return f(b,a)})}function f(a,b){return b.split("").map(function(b,c){return d.Oa(c,a,b)})}var d=e(6),a=e(5),k=[3,4,5,6,7,8,9].map(function(a){return{id:"hex-"+a+"-4",event:"onclick",
action:{f:1,b:0,active:0,a:{}}}}).concat([1,2,3,4,5,6].map(function(a){return{id:"hex-"+a+"-5",event:"onclick",action:{f:12,b:0,active:0,a:{}}}})),l="####   ## ;### Glitch;##  Squad;##  ;###HOTSEAT;#ONLINE###".split(";").map(function(a,b){return f(b,a)});c.R=function(c,d){return{location:0,local:!0,i:a.qa(d?b(c,d):l),m:k,c:[],g:[],ga:c?c:!1}};c.pa=f},function(h,c){c.da=function(c,b){switch(c.N){case 1:setTimeout(function(){return b(c.a)},200);break;case 2:setTimeout(function(){return b(c.a)},500)}}},
function(h,c,e){function b(a){var b=a.c,c=a.active;if(!b||8!==b.length)return a;if(-1<c&&!b.find(function(a){return a.b!==b[c].b&&!a.w}))return l(b[c].b,a);a.active=(a.active+1)%a.c.length;var d=a.c[a.active];!0===d.w?d.A=0:d.A=d.X;return d.w?g(u.M(a)):u.M(a)}function f(a){var b=a.c[a.active];b.x===a.u[0]&&b.y===a.u[1]&&(a.c.map(function(a){return Object.assign(a,{u:!1})}),b.u=!0);return u.M(n(a))}function d(b,c){var g=c.c[c.active],g=b.Z.reduce(function(b,c){return a(b.x,b.y,c,b.t,b.state)},{x:g.x,
y:g.y,t:0,state:c});return p(g.state)}function a(a,b,c,g,d){var e=d.i[c.y][c.x],f=d.c,k=f[d.active];g=1!==c.type&&2!==c.type||k.x===a&&k.y===b?g+3:g+10;c.x===a&&c.y===b||e.c.forEach(function(a){g=g+5;if(f[a].w)"";else{var b=d,c=100*Math.random()>g,e=c&&50<g||!c&&50>g;c?(b=e?A(b):b,b.c[a].w=!0,b.c[a].A=0,a=b):a=e?A(b):b;d=a}});return{x:c.x,y:c.y,t:g,state:d}}function k(a,b){return a.Z.reduce(function(a,c){var g;2===c.type?(a.i[c.y][c.x].v[c.d]=1,g=a):g=b;return g},b)}function l(a,b){b.g.push({N:1,
a:{f:11,active:b.active,b:a,a:{$:a}}});return b}function m(a,b){return r.R(a,b.c.filter(function(b){return b.b===a}))}function p(a){a.c[a.active].A=0;return g(a)}function n(a){var b=a.c[a.active];b.A=b.A-1;return b.A?a:g(a)}function g(a){a.m=[];a.g.push({N:1,a:{f:3,active:a.active,b:a.c[a.active].b,a:{}}});return a}function q(a){return a.c&&0<a.c.length&&-1<a.active?!a.c[a.active].w:!1}function A(a){a.g.push({N:1,a:{f:10,active:a.active,b:a.c[a.active].b,a:{}}});return a}var u=e(12),D=e(13),r=e(9);
c.ea=function(a,c){switch(c.f){case 3:return b(a);case 4:var g;if(q(a)){g=c.a.x;var e=c.a.y,h=a.c[a.active];h.x=g;h.y=e;if(h.u){var r=B(a.u),h=r.next().value,r=r.next().value,h=a.i[r][h],r=a.i[e][g];3!==h.type?h.type=1:"";3!==r.type?r.type=4:"";a.u=[g,e]}g=u.M(n(D.Ka(a)))}else g=b(a);return g;case 5:return q(a)?(g=c.a.Fa,a.i[g.sa][g.ra].v[g.oa]=1,g=u.M(n(a))):g=b(a),g;case 6:return q(a)?f(a):b(a);case 11:return q(a)?m(c.a.$,a):b(a);case 9:return q(a)?l(c.a.$,a):b(a);case 7:return q(a)?d(c.a,a):b(a);
case 8:return q(a)?(g=c.a,g=d(g,k(g,a))):g=b(a),g;default:return a}};c.Ja=b},function(h,c,e){function b(a){p(a,6)?a.m.push({id:"evac-"+a.active,display:"EVAC",event:"onclick",action:{f:9,active:a.active,b:a.c[a.active].b,a:{$:a.c[a.active].b}}}):"";return a}function f(a){p(a,4)?a.m.push({id:"grab-"+a.active,display:"GRAB",event:"onclick",action:{f:6,active:a.active,b:a.c[a.active].b,a:{}}}):"";return a}function d(a){p(a,5)?a.m.push({id:"skip-"+a.active,display:"SKIP",event:"onclick",action:{f:3,active:a.active,
b:a.c[a.active].b,a:{}}}):"";return a}function a(a){var b=a.c,c=b[a.active],d=c.x,e=c.y,f=c.b;if(!p(a,1))return a;Array.from(Array(6),function(b,c){return n.aa(d,e,c,a.i,2)}).filter(function(c){return-1<c.findIndex(function(c){return-1<a.i[c.y][c.x].c.findIndex(function(a){return b[a].b!==f&&!b[a].w})})}).forEach(function(b){var c={id:"hex-"+b[b.length-1].x+"-"+b[b.length-1].y+"-"+b[b.length-1].d+"-shoot_rifle",display:"SHOOT",color:"darkred sd-"+b[b.length-1].d,event:"onclick",action:{f:7,active:a.active,
b:f,a:{Z:b}}};a.m.push(c);a.i[b[b.length-1].y][b[b.length-1].x].G.push(c)});return a}function k(a){var b=a.c[a.active],c=b.x,d=b.y,e=b.b;if(!p(a,2,2))return a;Array.from(Array(6),function(b,e){return n.aa(c,d,e,a.i,3)}).filter(function(a){return 0<a.length}).forEach(function(b){var c={id:"hex-"+b[b.length-1].x+"-"+b[b.length-1].y+"-"+b[b.length-1].d+"-shoot_heavy",display:"BARRAGE",color:"darkred sd-"+b[b.length-1].d+" heavy",event:"onclick",action:{f:8,active:a.active,b:e,a:{Z:b}}};a.m.push(c);a.i[b[b.length-
1].y][b[b.length-1].x].G.push(c)});return a}function l(a){var b=a.c[a.active],c=b.x,d=b.y,e=b.b;if(!p(a,3))return a;Array.from(Array(6),function(b,e){return n.xa(c,d,e,a.i)}).filter(function(a){return!!a}).forEach(function(b){var c={id:"hex-"+b.ra+"-"+b.sa+"-"+b.oa+"-hack",display:"HACK",color:"darkgrey",event:"onclick",action:{f:5,active:a.active,b:e,a:{Fa:b}}};a.m.push(c);a.i[b.Ca][b.Ba].G.push(c)});return a}function m(a){var b=a.c[a.active],c=b.x,d=b.y,e=b.b;if(!p(a,0))return a;Array.from(Array(6),
function(b,e){var f=a.i,k=n.fa(c,d,e),l=k.x,k=k.y;return n.wa(c,d,e,f)?{x:l,y:k}:!1}).filter(function(a){return!!a}).forEach(function(b){var c=b.x,d=b.y,c={id:"hex-"+c+"-"+d+"-4",display:"MOVE",color:"p"+e,event:"onclick",action:{f:4,active:a.active,b:e,a:{x:c,y:d}}};a.m.push(c);a.i[b.y][b.x].G.push(c)});return a}function p(a,b,c){a=a.c[a.active];var d=a.A,e=a.ma;return!a.w&&d>=(void 0===c?1:c)&&-1<e.indexOf(b)}var n=e(7);c.M=function(c){c.m=[];c.i.forEach(function(a){return a.forEach(function(a){return a.G=
[]})});return k(a(b(f(l(m(d(c)))))))}},function(h,c,e){function b(a){a.i.forEach(function(a){return a.forEach(function(a){return a.c=[]})});a.c.forEach(function(b){return a.i[b.y][b.x].c.push(b.F)});return a}function f(a){a.c.forEach(function(a,b){return a.F=b});return a}var d=e(14);c.za=function(a){function c(a,b){function e(a,b){return b.V-a.V}var f=function(a){return[d.Y(a),d.Y(a),d.Y(a),d.Na(a)]}(a).sort(e);b.c=b.c.concat(f).sort(e);b.i.forEach(function(b){return b.forEach(function(b){return b.b===
a?f.forEach(function(a){a.x=b.x;a.y=b.y}):""})});return b}return b(f(c(0,c(1,a))))};c.Ka=b;c.$a=f},function(h,c,e){var b=e(15).ua.split(",");c.Y=function(c){return{type:1,code:"SQ",A:2,X:2,V:5+5*Math.random(),w:!1,ma:[6,0,1,3,4,5],b:c,name:b[Math.floor(Math.random()*b.length)],x:1,y:1,F:0}};c.Na=function(c){return{type:0,code:"HE",A:1,X:2,V:2+5*Math.random(),w:!1,ma:[6,0,2,3,4,5],b:c,name:b[Math.floor(Math.random()*b.length)],x:1,y:1,F:0}}},function(h,c){c.ua="Alice,Artur,Ben,Bony,Chris,Clara,Dave,Daisy,Eugene,Elisa,Frank,Faye,Glen,Gene,Gideon,Ghandi,Henry,Hanna,Izac,Ida,Jack,Julia,Kevin,Kate,Lee,Lena,Matt,Martha,Nick,Nina,Odin,Olga,Pete,Pati,Ron,Rose,Stan,Suzie,Tom,Tracy,Uma,Ugo,Wayne,Wanda,Xena,Xavier,Yuri,Yara,Zack,Zoe"},
function(h,c,e){var b=e(17),f=e(9),d=["####   ## ","CONNECTING","Squad","##  "].map(function(a,b){return f.pa(b,a)});c.ka=function(a,c){switch(c.f){case 1:return b.U();case 12:return a.i=d,a.local=!1,a;default:return a}}},function(h,c,e){var b=e(5),f=e(13),d=e(11);c.U=function(){var a={location:1,i:b.Ha(),m:[],g:[{N:0,a:{}}],c:[],active:-1,ga:!1,local:!0,u:[],S:[[],[]]};a.i.forEach(function(b){return b.forEach(function(b){switch(b.type){case 4:return a.u=[b.x,b.y];case 3:return 0===b.b?a.S[0]=[b.x,
b.y]:a.S[1]=[b.x,b.y]}})});return d.Ja(f.za(a))}},function(h,c,e){var b=e(3),f=e(19),d=e(9),a=e(20),k=e(23),l=e(10),m=e(11),p=e(16),n=e(17);c.start=function(c){var e=d.R();n.U();c=b.Ga([a.Ia,k.Da],c);var h=b.ia([p.ka,m.ea]),u=b.ha([l.da]);new f.ta(e,c,b.D,h,u)}},function(h,c,e){function b(a,b,c,d,e){this.state=a;this.j=b;this.D=c;this.o=d;this.C=e;this.B=[];this.h=this.h.bind(this);this.s=this.s.bind(this);this.j=this.j.bind(this);this.o=this.o.bind(this);this.D=this.D.bind(this);this.C=this.C.bind(this);
this.h({f:0,active:0,b:0,a:{}});this.P()}var f=e(9),d=e(3);b.prototype.h=function(a){if(!0===this.state.local){12===a.f&&this.l.emit("waiting");if(10===a.f||4<this.B.length&&.985<Math.random())return this.s(d.H(this.W),[].concat(C(this.B)));var b=this.o(this.state,a);this.K(b,a);this.j(b);this.D(b.m,this.h);this.C(-1<b.g.findIndex(function(a){return a.a&&10===a.a.f})?b.g.filter(function(a){return a.a&&10===a.a.f}):b.g,this.h);b.g=[];this.state=b}else this.I(a)};b.prototype.I=function(a){this.l.emit("action",
a)};b.prototype.K=function(a,b){1===b.f?(this.W=d.H(a),this.B=[]):11!==b.f?this.B.push(b):""};b.prototype.s=function(a,b){var c=b.shift();a.active=c.active;if(0<b.length){var d=this;a.s=!0;var e=this.o(a,c);this.j(e);e.g=[];setTimeout(function(){return d.s(e,b)},140)}else a.s=!1,c=this.o(a,c),this.j(c),c.g=c.g.filter(function(a){return a.a?10!==a.a.f:!0}),c.g=-1<c.g.findIndex(function(a){return a.a&&11===a.a.f})?c.g.filter(function(a){return a.a&&3===a.a.f}):c.g,this.D(c.m,this.h),this.C(c.g,this.h),
this.state=c};b.prototype.P=function(){var a=this;this.l=window.io({bb:!1,ab:["websocket"]});this.l.on("state",function(b){a.state=b;a.j(b);a.D(b.m,a.h)});this.l.on("connect",function(){});this.l.on("disconnect",function(){a.state=f.R();a.h({f:0,active:0,b:0,a:{}});alert("disconnected")});this.l.on("error",function(){a.state=f.R();a.h({f:0,active:0,b:0,a:{}});alert("server error")})};c.ta=b},function(h,c,e){var b=e(21);c.Ia=function(c){return 0===c.location?'\n\t    <div class="menu-hex"> '+b.ja(c)+
"\n\t    <div>\n\t ":""}},function(h,c,e){var b=e(22);c.ja=function(c){function d(a,d){function e(a){function d(a){return a.reduce(function(a,b,c){return a+('<div class="hw hw-a-'+c+" hw-t-"+b+'"></div>')},"")}return'<li class="hex '+(0===a.type?"empty":"")+'" id="hex-'+a.x+"-"+a.y+'">'+(""+(0!==a.type?d(a.v):""))+(""+b.na(a.c,c))+(""+(2===a.type&&" "!==a.char?'<div class="char">'+a.char+"</div>":""))+(""+(4===a.type?'<div class="evac disc">DATA</div>':""))+(""+(3===a.type?'<div class="evac c-p'+
a.b+'">evac</div>':""))+(""+function(a){return'<div class="h-acts l'+a.length+'">'+a.reduce(function(a,b){return a+('<div class="h-act '+b.color+'" id="'+b.id+'"><span>'+b.display+"</span></div> ")},"")+"</div>"}(a.G))+"</li>"}return'<ol class="hexline hexline-'+(d%2?"even":"odd")+'">'+a.reduce(function(a,b){return a+e(b)},"")+"</ol>"}return'<div id="hexmap" class="hexcontainer">'+c.i.reduce(function(a,b,c){return a+d(b,c)},"")+"</div>"}},function(h,c){c.na=function(c,b,f){function d(a){function c(){function d(b){return a.x===
b[0]&&a.y===b[1]}return'<div class="acts"><div class="ap">AP: '+a.A+"/"+a.X+"</div>"+(' <div id="skip-'+a.F+'">SKIP</div>')+(""+(d(b.u)&&!a.u?'<div class="s-action" id="grab-'+a.F+'"}>GRAB</div>':""))+((a.u&&d(b.S[a.b])?'<div class="s-action" id="evac-'+a.F+'">EVAC</div>':"")+" </div>")}var d=a.F===b.active;return'<div class="soldier s-t-'+a.type+" s-p-"+a.b+" s-m-"+(a.b===b.O?"i":"e")+((a.w?" s-kia":"")+" "+(d?" s-act":"")+" "+(a.u?" s-data":"")+'">')+('<div class="s-code">'+a.code+'</div> <div class="s-name">'+
a.name+"</div>")+(""+(f&&d?'<div class="s-player"> P'+(a.b+1)+"</div>":""))+(""+(f&&d&&!a.w&&a.A?c():""))+"</div>"}return'<div class="soldiers">'+c.reduce(function(a,c){return a+d(b.c[c])},"")+"</div>"}},function(h,c,e){var b=e(21),f=e(22);c.Da=function(c){1===c.location?(console.log(c.O),c='<div class="game-play '+(c.s?"glitch":"")+" "+(void 0===c.O?"hotseat":"online")+'">'+('<div class="game-hex"> '+b.ja(c)+"</div>")+('<div class="squads-display"> '+f.na([0,1,2,3,4,5,6,7],c,!0)+"</div>")+"</div>"):
c="";return c}},function(){}]);
