(function(){var b=b||{};b.TextureCache=[];b._hitList=[];b.Game=function(a,c,d){this.width=a||320;this.height=c||480;this.bgColor=d||"#000000";this.__updateList=[];this._isTouch=!1;"ontouchstart"in window&&(this._isTouch=!0);this.createCanvas();this.context=this.getContext();this.setSmoothing(!1);this.pointer={x:-1,y:-1,isDown:!1,isOut:!0};this.canvasRect=this.canvas.getBoundingClientRect();this.stage=new b.Stage(this.width,this.height);this.render();this.bindEvents()};b.Game.prototype={createCanvas:function(){this.canvas=
document.createElement("canvas");this.canvas.setAttribute("width",this.width);this.canvas.setAttribute("height",this.height);this.canvas.style.backgroundColor=this.bgColor;this.canvas.style.cursor="inherit";document.body.appendChild(this.canvas);this._isTouch&&(this.canvas.style.width=window.innerWidth+"px",this.canvas.style.height=window.innerHeight+"px")},setSmoothing:function(a){this.context.imageSmoothingEnabled=a;this.context.mozImageSmoothingEnabled=a;this.context.oImageSmoothingEnabled=a;this.context.webkitImageSmoothingEnabled=
a;this.context.msImageSmoothingEnabled=a},getContext:function(){return this.canvas.getContext("2d")},checkHits:function(){for(var a=b._hitList.length-1;0<=a;a--)if(!1!==b._hitList[a].active&&b._hitList[a].contains(this.pointer)){if(b._hitList[a].onPointerDown)b._hitList[a].onPointerDown(this.pointer);break}},bindEvents:function(a){var b=this,d,e;this._isTouch?(a="touchstart",d="touchmove",e="touchend"):(a="mousedown",d="mousemove",e="mouseup");this.canvas.addEventListener(d,this.moveHandler.bind(this),
!1);this.canvas.addEventListener(a,this.downHandler.bind(this),!1);this.canvas.addEventListener(e,this.upHandler.bind(this),!1);this.canvas.addEventListener("mouseout",function(){b.pointer.isDown=!1;b.pointer.isOut=!0},!0)},getPointerPosition:function(a){a=this._isTouch?a.targetTouches[0]:a;this.pointer.x=this.width/this.canvasRect.width*(a.clientX-this.canvasRect.left);this.pointer.y=this.height/this.canvasRect.height*(a.clientY-this.canvasRect.top);for(a=b._hitList.length-1;0<=a;a--)if(!1!==b._hitList[a].active)if(b._hitList[a].contains(this.pointer)){this.canvas.style.cursor=
"pointer";break}else this.canvas.style.cursor="inherit"},moveHandler:function(a){a.preventDefault();this.pointer.isOut=!1;this.getPointerPosition(a)},downHandler:function(a){a.preventDefault();this.getPointerPosition(a);this.pointer.isDown=!0;this.checkHits()},upHandler:function(a){a.preventDefault();this.pointer.isDown=!1},render:function(){requestAnimFrame(this.render.bind(this));this.context.fillStyle="#000000";this.context.fillRect(0,0,this.width,this.height);for(var a in this.__updateList)this.__updateList[a]();
b.Tweener.update();for(a=0;a<this.stage.children.length;a++)this.draw(this.stage.children[a])},draw:function(a){if(!(!1===a.visible||0>=a.alpha||null===a.parent)){this.context.save();this.context.globalAlpha=a.alpha;this.context.translate(a.x,a.y);this.context.rotate(a.rotation);a.render&&a.render(this.context);a._renderable&&1==a._loaded&&(null===a._crop?this.context.drawImage(a.texture,-a.width*a.anchorX,-a.height*a.anchorY,a.width,a.height):this.context.drawImage(a.texture,a._crop.cx,a._crop.cy,
a._crop.cw,a._crop.ch,0,0,a._crop.cw,a._crop.ch));if(a.children&&0<a.children.length)for(var b=0;b<a.children.length;b++)this.draw(a.children[b]);this.context.restore()}},addUpdate:function(a,b){"function"==typeof b&&(this.__updateList[a]=b)},removeUpdate:function(a){this.__updateList[a]=null},removeAllUpdates:function(a){this.__updateList=[]}};b.createCanvas=function(a,b){var d=document.createElement("canvas");d.width=a;d.height=b;d.style.display="none";document.body.appendChild(d);var e=d.getContext("2d");
return{canvas:d,context:e}};b.imageFromCanvas=function(a){a=a.toDataURL("image/png");var b=new Image;b.src=a;return b};b.removeCanvas=function(a){a.parentNode.removeChild(a)};b.HitArea=function(a,c,d,e){this.x=a;this.y=c;this.width=d;this.height=e;this.active=!0;this.onPointerOut=this.onPointerUp=this.onPointerDown=null;b._hitList.push(this)};b.HitArea.prototype.contains=function(a){return a.x>=this.x&&a.x<=this.x+this.width&&a.y>=this.y&&a.y<=this.y+this.height?!0:!1};b.HitArea.prototype.remove=
function(){b._hitList.splice(b._hitList.indexOf(this),1)};b.DisplayObject=function(){this.parent=this.stage=null;this.visible=!0;this._renderable=!1;this.y=this.x=0;this.scaleY=this.scaleX=1;this.rotation=0;this._alpha=1;this._height=this._width=null};Object.defineProperties(b.DisplayObject.prototype,{width:{get:function(){return this._width*this.scaleX},set:function(a){this._width=a}},height:{get:function(){return this._height*this.scaleY},set:function(a){this._height=a}},alpha:{get:function(){return this.parent._alpha*
this._alpha},set:function(a){this._alpha=a}}});b.DisplayObjectContainer=function(){b.DisplayObject.call(this);this.children=[]};b.DisplayObjectContainer.prototype=Object.create(b.DisplayObject.prototype);b.DisplayObjectContainer.prototype.constructor=b.DisplayObjectContainer;b.DisplayObjectContainer.prototype.addChild=function(a,b){a.parent&&a.parent.removeChild(a);a.parent=this;void 0===b?this.children.push(a):this.children.splice(b,0,a)};b.DisplayObjectContainer.prototype.removeChild=function(a){if(a.parent===
this)return this.children.splice(this.children.indexOf(a),1)};b.DisplayObjectContainer.prototype.removeAll=function(){for(;this.children.length;)this.removeChild(this.children[0])};b.DisplayObjectContainer.prototype.applyParams=function(a){for(var b in a)this[b]=a[b];return this};b.DisplayObjectContainer.prototype.addTo=function(a){a.addChild(this);return this};b.Stage=function(a,c){b.DisplayObjectContainer.call(this);this.stage=!0;this.parent=this;this.width=a;this.height=c};b.Stage.prototype=Object.create(b.DisplayObjectContainer.prototype);
b.Stage.prototype.constructor=b.Stage;b.Sprite=function(a,c){var d=this;b.DisplayObjectContainer.call(this);this._renderable=!0;this.anchorY=this.anchorX=.5;this._crop=this.height=this.width=null;this._loaded=!1;if(void 0!==b.TextureCache[a])this.texture=b.TextureCache[a],this.width=b.TextureCache[a].width,this.height=b.TextureCache[a].height,void 0!=c&&null==this._crop&&(this._crop=c),this._loaded=!0;else{var e=new Image;b.TextureCache[a]=e;e.onload=function(){d.texture=this;d.width=this.width;d.height=
this.height;void 0!=c&&null==d._crop&&(d._crop=c);d._loaded=!0};e.src=a}};b.Sprite.prototype=Object.create(b.DisplayObjectContainer.prototype);b.Sprite.prototype.constructor=b.Sprite;b.Sprite.prototype.setCrop=function(a){this._crop=a};b.Rectangle=function(a,c){b.DisplayObjectContainer.call(this);this._width=a;this._height=c;this.fillStyle="#DD6020";this.anchorY=this.anchorX=.5};b.Rectangle.prototype=Object.create(b.DisplayObjectContainer.prototype);b.Rectangle.prototype.constructor=b.Rectangle;b.Rectangle.prototype.render=
function(a){a.fillStyle=this.fillStyle;a.fillRect(-this.width*this.anchorX,-this.height*this.anchorY,this.width,this.height)};b.Line=function(a,c,d,e){b.DisplayObject.call(this);this.x1=a;this.y1=c;this.x2=d;this.y2=e;this.strokeStyle="#FFFFFF";this.lineWidth=1};b.Line.prototype=Object.create(b.DisplayObject.prototype);b.Line.prototype.constructor=b.Line;b.Line.prototype.render=function(a){a.strokeStyle=this.strokeStyle;a.lineWidth=this.lineWidth;a.beginPath();a.moveTo(this.x1,this.y1);a.lineTo(this.x2,
this.y2);a.stroke()};b.BitmapText=function(a,c){b.DisplayObjectContainer.call(this);this._pool=[];this.font=c;this.xAdvance=this.font.texture.data["0"].width;this.yAdvance=this.font.texture.data["0"].height;this.spacing=this.font.size;this.setText(a)};b.BitmapText.prototype=Object.create(b.DisplayObjectContainer.prototype);b.BitmapText.prototype.constructor=b.BitmapText;b.BitmapText.prototype.setText=function(a){this.text=a;this.updateText()};b.BitmapText.prototype.updateText=function(){var a,c;this.oldChilds=
this.children.length;for(var d=0;d<this.text.length;d++)a=this.text[d],c=d<this.oldChilds?this.children[d]:this._pool.pop(),a={cx:this.font.texture.data[a].x,cy:this.font.texture.data[a].y,cw:this.font.texture.data[a].width,ch:this.font.texture.data[a].height},c?c.setCrop(a):c=new b.Sprite(this.font.texture.img.src,a),c.x=d*(this.xAdvance+this.spacing),c.parent||this.addChild(c);for(;this.children.length>this.text.length;)c=this.children[this.children.length-1],this._pool.push(c),this.removeChild(c),
this._pool[this._pool.length-1].parent=void 0;this.textWidth=this.text.length*(this.xAdvance+this.spacing);this.textHeight=5*this.font.size};b.Tweener=b.Tweener||function(){var a=[];return{add:function(b){a.push(b)},getAll:function(){return a},update:function(){if(0!==a.length)for(i=0;i<a.length;i++)a[i].update()},remove:function(b){b=a.indexOf(b);-1!==b&&a.splice(b,1)},removeAll:function(){a=[]}}}();b.Tweener.Tween=function(a){var c=1E3,d={},e={},f=0,g=0,h=!1,l=0,m=null,n=null,p=null,q=null,s="Cubic",
r;for(r in a)d[r]=a[r];this.playing=!1;this.start=function(){this.playing=!0;m=Date.now()+f;b.Tweener.add(this);return this};this.to=function(a,b){e=a;c=b;return this};this.update=function(){if(!0===this.playing){var f=Date.now();if(!(f<m)){f=(f-m)/c;if(1<f){for(var k in e)a[k]=e[k];if(0<g){isFinite(g)&&g--;if(h){for(k in e)f=d[k],d[k]=e[k],e[k]=f;null!==n&&n.call()}m=Date.now()+l}else this.stop(),null!==q&&q()}else for(k in f=b.Easing[s](f),e)a[k]=d[k]*(1-f)+e[k]*f;null!==p&&p.call()}}};this.easing=
function(a){s=a;return this};this.delay=function(a){f=a;return this};this.repeat=function(a,b){g=a;void 0!==b&&(l=b);return this};this.yoyo=function(a,b){h=a;return this};this.onYoyo=function(a){n=a;return this};this.onUpdate=function(a){p=a;return this};this.onComplete=function(a){q=a;return this};this.stop=function(){this.playing=!1;b.Tweener.remove(this)};return this};b.Easing={Linear:function(a){return a},Cubic:function(a){return 1>(a*=2)?.5*a*a*a:.5*((a-=2)*a*a+2)}};null==window.requestAnimFrame&&
(window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}());"undefined"!==typeof exports?("undefined"!==typeof module&&module.exports&&(exports=module.exports=b),exports.MGE=b):this.MGE=b}).call(this);
(function(){var b=b||{};b.TYPES={FIRE:0,WATER:1,EARTH:2,AIR:3};b.CURRENTENEMY=0;b.OPPONENTS=[{attack:300,health:1,type:"EARTH",weakness:"AIR",active:!0,enemy:!0},{attack:340,health:1700,type:"AIR",weakness:"EARTH",active:!0,enemy:!0},{attack:380,health:1900,type:"FIRE",weakness:"WATER",active:!0,enemy:!0},{attack:410,health:2100,type:"WATER",weakness:"FIRE",active:!0,enemy:!0}];var a;b.Start=function(){a=new MGE.Game;new b.MakeImages;b.CreateLayers(a);a.smallFont=new b.MakeFont({color:"#FFFFFF",shadow:"#ae4a12",
size:1});a.smallFontGrey=new b.MakeFont({color:"#FFFFFF",shadow:"#303030",size:1});a.comboFont=new b.MakeFont({color:"#b80000",shadow:"#FFFFFF",size:4});a.font=new b.MakeFont({color:"#FFFFFF",shadow:"#505050",size:2});a.font.onComplete=b.initTextures};b.initTextures=function(){a.player=(new b.Player(a,MGE.TextureCache.angel.src,{attack:10,health:2E3,type:"FIRE",weakness:"WATER",active:!0,enemy:!1})).applyParams({x:64,y:97}).addTo(a.playersContainer);a.moves=new b.Moves(a,a.gameLayer);var c=new MGE.BitmapText("VS",
a.font);c.applyParams({x:a.width/2-c.textWidth/2,y:92}).addTo(a.gameLayer);(new b.Button("INVENTORY - "+a.player.inventory.length+" ITEMS",a.font,314,30)).applyParams({x:160,y:196}).addTo(a.playgroundContainer);(new b.Chessboard(6,5,51,6,["#e9f1f6","#c6def0"])).applyParams({x:160,y:345}).addTo(a.playgroundContainer);(new b.Button("",a.smallFont,310,200,["#FFFFFF","#404040","#404040"])).applyParams({x:a.width/2,y:314}).addTo(a.inventoryContainer);(new b.Button("YOU HAVE NO ITEMS TO USE",a.smallFontGrey,
310,27,["#FFFFFF","#404040","#404040"])).applyParams({x:a.width/2,y:430}).addTo(a.inventoryContainer);(new b.Button("CANCEL",a.font,154,30)).applyParams({x:81,y:462}).addTo(a.inventoryContainer);(new b.Button("",a.font,200,200,["#FFFFFF","#ae4a12","#DD6020"])).applyParams({x:a.width/2,y:240}).addTo(a.overLayer);a.overLayer.overText=new MGE.BitmapText("YOU WIN!",a.font);a.overLayer.overText.applyParams({x:a.width/2-a.overLayer.overText.textWidth/2,y:160}).addTo(a.overLayer);a.overLayer.overText2=new MGE.BitmapText("PREPARE FOR",
a.font);a.overLayer.overText2.applyParams({x:a.width/2-a.overLayer.overText2.textWidth/2,y:220}).addTo(a.overLayer);a.overLayer.overText3=new MGE.BitmapText("NEXT ROUND",a.font);a.overLayer.overText3.applyParams({x:a.width/2-a.overLayer.overText3.textWidth/2,y:a.overLayer.overText2.y+20}).addTo(a.overLayer);a.overLayer.continueButton=(new b.Button("CONTINUE",a.font,160,30,["#4f2f03","#FFFFFF","#46cd21"])).applyParams({x:160,y:304}).addTo(a.overLayer);a.overLayer.area=new MGE.HitArea(0,0,320,480);
a.overLayer.area.active=!1;new b.Intro(a,a.introLayer)};b.initCachedTextures=function(){a.introLayer.visible=!1;(new b.Button("CLOSE INVENTORY",a.font,314,30)).applyParams({x:160,y:196}).addTo(a.inventoryContainer);(new b.Button("USE ITEM",a.font,154,30)).applyParams({x:239,y:462}).addTo(a.inventoryContainer);a.elementsContainer=new MGE.DisplayObjectContainer;a.playgroundContainer.addChild(a.elementsContainer);a.grid=new b.Grid(6,5,[0,1,2,3]);a.elements=new b.Elements(a,a.playgroundContainer,0);a.gameLayer.visible=
!0;b.startGame()};b.createOpponent=function(){void 0!==a.opponent&&a.playersContainer.removeChild(a.opponent);a.opponent=(new b.Player(a,MGE.TextureCache.dragon.src,b.OPPONENTS[b.CURRENTENEMY])).applyParams({x:256,y:97}).addTo(a.playersContainer)};b.startGame=function(){b.createOpponent();a.moves.setMoves(a.player.moves.toString());(new MGE.HitArea(0,181,320,30)).onPointerDown=function(){0<a.player.moves&&(a.playgroundContainer.visible?(a.playgroundContainer.visible=!1,a.elements.interactive(!1),
a.inventoryContainer.visible=!0):(a.playgroundContainer.visible=!0,a.elements.interactive(!0),a.inventoryContainer.visible=!1))}};window.onload=function(){b.Start()};"undefined"!==typeof exports?("undefined"!==typeof module&&module.exports&&(exports=module.exports=b),exports.FE=b):this.FE=b}).call(this);
FE.CreateLayers=function(b){b.introLayer=new MGE.DisplayObjectContainer;b.stage.addChild(b.introLayer);b.menuLayer=new MGE.DisplayObjectContainer;b.menuLayer.visible=!1;b.stage.addChild(b.menuLayer);b.gameLayer=new MGE.DisplayObjectContainer;b.gameLayer.visible=!1;b.stage.addChild(b.gameLayer);b.playersContainer=new MGE.DisplayObjectContainer;b.gameLayer.addChild(b.playersContainer);b.playgroundContainer=new MGE.DisplayObjectContainer;b.gameLayer.addChild(b.playgroundContainer);b.inventoryContainer=
new MGE.DisplayObjectContainer;b.inventoryContainer.visible=!1;b.gameLayer.addChild(b.inventoryContainer);b.overLayer=new MGE.DisplayObjectContainer;b.overLayer.visible=!1;b.stage.addChild(b.overLayer)};
FE.MakeFont=function(b){this.color=b.color;this.shadow=b.shadow;this.size=b.size;this.name=b.name;this.data=[];this.numChars=Object.keys(FE.fontData).length;this.perLineX=Math.round(Math.sqrt(this.numChars))+1;this.perLineY=this.perLineX*this.perLineX<this.numChars?this.perLineX+1:this.perLineX;b=MGE.createCanvas(5*this.size*this.perLineX,(5*this.size+(null==this.shadow?0:this.size))*this.perLineY);this.canvas=b.canvas;this.context=b.context;this.start()};
FE.MakeFont.prototype={start:function(){var b=this,a,c,d,e=0,f;for(f in FE.fontData){for(var g=FE.fontData[f],h=0;5>h;h++){a=g&31;for(var l=0;5>l;l++)c=e%this.perLineX*5*this.size+l*this.size,d=5*~~(e/this.perLineX)*this.size+h*this.size+(null==this.shadow?0:~~(e/this.perLineX)*this.size),16===(a&16)&&(null!=this.shadow&&(this.context.fillStyle=this.shadow,this.context.fillRect(c,d+this.size,this.size,this.size)),this.context.fillStyle=this.color,this.context.fillRect(c,d,this.size,this.size)),a<<=
1;g>>=5}e++;this.data[f]={x:c-4*this.size,y:d-4*this.size,width:5*this.size,height:null==this.shadow?5*this.size:6*this.size}}var m=MGE.imageFromCanvas(this.canvas);m.onload=function(){MGE.TextureCache[m.src]=m;b.storeImage(m,b.data)}},storeImage:function(b,a){this.texture={img:b,data:a};MGE.removeCanvas(this.canvas);this.onComplete&&this.onComplete.call()}};
FE.fontData={0:15255086,1:2165186,2:33061951,3:32554047,4:1113649,5:32570911,6:33095199,7:1082431,8:33095231,9:32570943,A:18859566,B:32045630,C:16269839,D:32032318,E:33061407,F:17332767,G:16309775,H:18415153,I:32641183,J:15238207,K:18444881,L:33047056,M:18405233,N:18470705,O:15255086,P:17778238,Q:16369198,R:18826814,S:31504911,T:4329631,U:15255089,V:4539953,W:11195953,X:18157905,Y:4336177,Z:32772191,"+":145536,"-":14336,"*":332096,":":131200,".":8388608,",":17301504,"?":4198476,"!":4198532,"|":4329604,
'"':330,"(":4464900,")":4261956," ":0};FE.Button=function(b,a,c,d,e){this._w=c;this._h=d;this.colors=e||["#4f2f03","#FFFFFF","#DD6020"];this.view=MGE.createCanvas(this._w,this._h);for(c=0;3>c;c++)this.view.context.fillStyle=this.colors[c],this.view.context.fillRect(c*a.size,c*a.size,this._w-2*c*a.size,this._h-2*c*a.size);MGE.Sprite.call(this,this.view.canvas.toDataURL("image/png"));MGE.removeCanvas(this.view.canvas);this.text=new MGE.BitmapText(b,a);this.setText(b);this.addChild(this.text)};
FE.Button.prototype=Object.create(MGE.Sprite.prototype);FE.Button.prototype.constructor=FE.Button;FE.Button.prototype._align=function(){this.text.x=-this.text.textWidth/2;this.text.y=~~(-this.text.textHeight/2)};FE.Button.prototype.setText=function(b){this.text.setText(b);this._align()};
FE.Chessboard=function(b,a,c,d,e){var f=b*c,g=a*c,h=MGE.createCanvas(f+d,g+d);(new MGE.Rectangle(f+d,g+d)).applyParams({anchorX:0,anchorY:0,fillStyle:"#FFFFFF"}).render(h.context);f=!1;for(g=0;g<a;g++){for(var l=0;l<b;l++)h.context.fillStyle=e[f?1:0],h.context.fillRect(d/2+l*c,d/2+g*c,c,c),f=!f;0==b%2&&(f=!f)}MGE.Sprite.call(this,h.canvas.toDataURL("image/png"));MGE.removeCanvas(h.canvas)};FE.Chessboard.prototype=Object.create(MGE.Sprite.prototype);FE.Chessboard.prototype.constructor=FE.Chessboard;
FE.MakeImages=function(b){this.numImages=Object.keys(FE.images).length;b=MGE.createCanvas(16,16);this.canvas=b.canvas;this.context=b.context;this.start()};FE.MakeImages.prototype={start:function(){for(var b in FE.images){for(var a in FE.images[b]){var c=FE.decodeImage(FE.images[b][a]);this.context.fillStyle=a;for(var d=0;16>d;d++)for(var e=0;16>e;e++)"1"==c[e+16*d]&&this.context.fillRect(e,d,1,1)}c=MGE.imageFromCanvas(this.canvas);MGE.TextureCache[b]=c;this.context.clearRect(0,0,16,16)}MGE.removeCanvas(this.canvas)}};
FE.encodeImage=function(b){var a=b[0];b.match(/(.)\1*/g).forEach(function(b){a+=String.fromCharCode(96+b.length)});return a};FE.decodeImage=function(b){for(var a="",c="0"===b[0]?!0:!1,d=1;d<b.length;d++)a+=Array(b.charCodeAt(d)-95).join(c?"0":"1"),c=!c;return a};
FE.images={angel:{"#88a1a7":"0\u00baaoazaofjfihoaoahht","#afd1d9":"0\u0084bmdkekhgigfjadbndldkfigig","#7a9196":"0\u00c8aoe\u00e3","#48727c":"0\u00a9blaoaoape\u0096aoaoaoid","#e0e6e7":"0\u0094bmdlcldld\u00ea","#bd9127":"0hdkcmbnbnb\u0117","#f8cea1":"0zbmcmc\u00a1a"},dragon:{"#20710f":"0\u0083aaamcmdkffabffabmdfldkigjfjeoanck","#46cd21":"0\u00a4andkegabgebdcagifjcmdnbmdld","#56320e":"0\u00c7apapapapapaoaparbdc","#ead873":"0\u0104bnbnbncmc","#dda621":"0\u0103aoaoaoaoapb","#0d0501":"0\u00b3aaa"},fire:{"#880000":"0vacahabaocleaaifgaaifkdlcnbn\u0083apkfic",
"#b80000":"0\u0087aoancmdaaighifjeldlcnbnoa","#f82f00":"0\u00b8anclekfhifjekelekfi","#f88800":"0\u00c8ancmdkfhhgigjfjgh","#ffffff":"0\u00e8aobmckaadjfigje"},water:{"#5174ad":"0yanbmclejfihgjfjeldldldldlejghd","#5989d7":"0\u00a9anbnclekekfigigigjfkdt","#87beec":"0\u0098anbnanbnaoanbnaoaoaobobx","#ffffff":"0\u00b6ananbnbmbnbnbnbnbobz"},air:{"#7d7dec":"0\u0087dihgkcnaoa\u0080aoanclfgj","#b4b9e3":"0\u0097dihgkdldmcmdlejge","#656eba":"0\u00b6efadadaeacacabadacacabaeacccaebgahaeaje","#ffffff":"0\u00c7ancmc"},
earth:{"#7cef5d":"0\u008eamcldjfhhfjdlcldlejghhf\u0086","#46cd21":"0oanambmambkckckcmanaoapa","#4ab034":"0\u007faoanbmaaalabakacajadahbeafbfafananamanaca","#61d740":"0\u00bdanbmbmckdcaffiekd\u0097","#2c9d14":"0\u010eabakadaiaebfbeacefao"},healthPotion:{"#9f6c2f":"0vdldlabalabalabalabakadaiafagahaeajadajadajadajaeahaghd"}};FE.emptyItem=function(){this.value=-1};FE.Grid=function(b,a,c){this.size={x:b,y:a,available:c};this.grid=[];this.initEmptyGrid();this.fillGrid()};
FE.Grid.prototype={initEmptyGrid:function(){for(var b=0;b<this.size.y;b++){this.grid[b]=[];for(var a=0;a<this.size.x;a++)this.setEmpty(b,a)}},fillGrid:function(){for(var b=0;b<this.size.y;b++)for(var a=0;a<this.size.x;a++){do this.grid[b][a].value=this.size.available[Math.floor(Math.random()*this.size.available.length)];while(this.isStreak(b,a))}},refillGrid:function(){for(var b=[],a=0;a<this.size.x;a++)-1==this.grid[0][a].value&&(this.setEmpty(0,a),this.grid[0][a].value=this.size.available[Math.floor(Math.random()*
this.size.available.length)],b.push({row:0,col:a}));return b},checkCombo:function(){for(var b=0,a=[],c=0;c<this.size.y;c++)for(var d=0;d<this.size.x;d++){if(d<=this.size.x-3&&-1!=this.grid[c][d].value&&this.grid[c][d].value==this.grid[c][d+1].value&&this.grid[c][d].value==this.grid[c][d+2].value){b++;var e=this.removeItems(c,d);if(0!=e.length)for(var f in e){var g=e[f];a.push(g)}}if(c<=this.size.y-3&&-1!=this.grid[c][d].value&&this.grid[c][d].value==this.grid[c+1][d].value&&this.grid[c][d].value==
this.grid[c+2][d].value&&(b++,e=this.removeItems(c,d),0!=e.length))for(f in e)g=e[f],a.push(g)}return{count:b,removed:a}},swap:function(b,a){var c=this.grid[b.row][b.col];this.grid[b.row][b.col]=this.grid[a.row][a.col];this.grid[a.row][a.col]=c},setEmpty:function(b,a){this.grid[b][a]=new FE.emptyItem},getItem:function(b,a){return this.grid[b][a].value},setItem:function(b,a,c){this.grid[b][a].value=c},removeItems:function(b,a){var c=this.grid[b][a].value,d=b,e=[];e.push({row:b,col:a,value:c});if(this.isVerticalStreak(b,
a)){for(;0<d&&this.grid[d-1][a].value==c;)e.push({row:d-1,col:a,value:c}),this.setEmpty(d-1,a),d--;for(d=b;d<this.size.y-1&&this.grid[d+1][a].value==c;)e.push({row:d+1,col:a,value:c}),this.setEmpty(d+1,a),d++}if(this.isHorizontalStreak(b,a)){for(d=a;0<d&&this.grid[b][d-1].value==c;)e.push({row:b,col:d-1,value:c}),this.setEmpty(b,d-1),d--;for(d=a;d<this.size.x-1&&this.grid[b][d+1].value==c;)e.push({row:b,col:d+1,value:c}),this.setEmpty(b,d+1),d++}this.setEmpty(b,a);return e},applyGravity:function(b){b=
[];for(var a=0;a<this.size.x;a++)for(var c=this.size.y-1;0<c;c--)-1==this.grid[c][a].value&&0<=this.grid[c-1][a].value&&(b.push({row:c-1,col:a}),this.grid[c][a]=this.grid[c-1][a],this.setEmpty(c-1,a));return b},isStreak:function(b,a){return this.isVerticalStreak(b,a)||this.isHorizontalStreak(b,a)},isVerticalStreak:function(b,a){for(var c=this.grid[b][a].value,d=0,e=b;0<e&&this.grid[e-1][a].value==c;)d++,e--;for(e=b;e<this.size.y-1&&this.grid[e+1][a].value==c;)d++,e++;return 1<d},isHorizontalStreak:function(b,
a){for(var c=this.grid[b][a].value,d=0,e=a;0<e&&this.grid[b][e-1].value==c;)d++,e--;for(e=a;e<this.size.x-1&&this.grid[b][e+1].value==c;)d++,e++;return 1<d},getRow:function(b){for(var a=[],c=0;c<this.size.x;c++)a.push(this.grid[b][c]);return a},debug:function(b){b=b||"value";for(var a=[],c=0;c<this.size.y;c++){for(var d="",e=this.getRow(c),f=0;f<e.length;f++)d+=e[f][b]+" ";a.push(d)}console.log("[Grid - debug]");for(c in a)console.log(a[c])}};
FE.Player=function(b,a,c){this.game=b;this.image=a;this.properties=c;this.health=this.properties.health;this.defaultMoves=this.properties.enemy?1:5;this.damages=[1,0,3,2];this.isDead=!1;this.moves=this.defaultMoves;this.inventory=[];this._activeColors=["#FFFFFF","#ae4a12","#DD6020"];this._inactiveColors=["#a0a0a0","#808080","#909090"];MGE.DisplayObjectContainer.call(this);this.draw()};FE.Player.prototype=Object.create(MGE.DisplayObjectContainer.prototype);FE.Player.prototype.constructor=FE.Player;
FE.Player.prototype.getDamage=function(b,a){var c=Math.round(a*(FE.TYPES[this.properties.type]==this.damages[b]?1.5:FE.TYPES[this.properties.type]==b?.5:1));this.health-=c;0>=this.health&&(this.health=0,this.isDead=!0,this.animateDeath());this.update();this.healthText.setText("HEALTH   : "+this.health);return c};
FE.Player.prototype.animateDeath=function(){var b=this,a={s:4,a:1};(new MGE.Tweener.Tween(a)).to({s:2,a:.5},1E3).onUpdate(function(){b.avatar.alpha=a.a;b.avatar.scaleX=a.s;b.avatar.scaleY=a.s}).start()};FE.Player.prototype.update=function(){0<=this.health&&this.health<=this.properties.health&&(this.healthBar.scaleX=this.health/this.properties.health);0>=this.health&&(this.healthBar.scaleX=0)};
FE.Player.prototype.reset=function(){this.health=this.properties.health;this.update();this.attackText.setText("ATTACK   : "+this.properties.attack);this.healthText.setText("HEALTH   : "+this.properties.health);this.typeText.setText("TYPE     : "+this.properties.type);this.weaknessText.setText("WEAKNESS : "+this.properties.weakness);this.avatar.applyParams({scaleX:4,scaleY:4,alpha:1});this.isDead=!1;this.moves=this.defaultMoves};
FE.Player.prototype.draw=function(){this.bg=(new FE.Button("",this.game.font,120,161,this.properties.active?this._activeColors:this._inactiveColors)).applyParams({}).addTo(this);this.healthBarBG=(new FE.Button("",this.game.smallFont,140,8,["#FFFFFF","#404040","#404040"])).applyParams({x:this.properties.enemy?-10:10,y:-88,visible:this.properties.active?!0:!1}).addTo(this);this.healthBar=(new MGE.Rectangle(138,6)).applyParams({x:this.properties.enemy?59:-59,y:-88,fillStyle:"#00DD00",visible:this.properties.active?
!0:!1,anchorX:this.properties.enemy?1:0}).addTo(this);this.avatar=(new MGE.Sprite(this.image)).applyParams({scaleX:4,scaleY:4,alpha:1,x:0,y:-20}).addTo(this);this.attackText=new MGE.BitmapText("ATTACK   : "+this.properties.attack,this.game.smallFont);this.attackText.applyParams({x:-48,y:34}).addTo(this);this.healthText=new MGE.BitmapText("HEALTH   : "+this.properties.health,this.game.smallFont);this.healthText.applyParams({x:-48,y:44}).addTo(this);this.typeText=new MGE.BitmapText("TYPE     : "+this.properties.type,
this.game.smallFont);this.typeText.applyParams({x:-48,y:54}).addTo(this);this.weaknessText=new MGE.BitmapText("WEAKNESS : "+this.properties.weakness,this.game.smallFont);this.weaknessText.applyParams({x:-48,y:64}).addTo(this)};FE.Intro=function(b,a){this.game=b;this.layer=a;this.draw();this.fadeIn()};
FE.Intro.prototype={draw:function(){this.title1=new MGE.BitmapText("SALVATION",this.game.font);this.title1.applyParams({x:this.game.width/2-this.title1.textWidth/2,y:214,alpha:0}).addTo(this.layer);this.title2=new MGE.BitmapText("OF FALLEN ANGEL",this.game.font);this.title2.applyParams({x:this.game.width/2-this.title2.textWidth/2,y:this.title1.y+20,alpha:0}).addTo(this.layer);this.title3=new MGE.BitmapText("BY ENEA ENTERTAINMENT",this.game.smallFontGrey);this.title3.applyParams({x:this.game.width/
2-this.title3.textWidth/2,y:this.title2.y+20,alpha:0}).addTo(this.layer);this.skip=new MGE.BitmapText((MGE._isTouch?"TOUCH":"CLICK")+" ANYWHERE TO CONTINUE",this.game.smallFontGrey);this.skip.applyParams({x:this.game.width/2-this.skip.textWidth/2,y:456,alpha:0}).addTo(this.layer);this.area=new MGE.HitArea(0,0,320,480);this.area.onPointerDown=function(){this.remove();MGE.Tweener.removeAll();FE.initCachedTextures()}},fadeIn:function(){var b=this,a={a:0},c={a:0},d={a:0};(new MGE.Tweener.Tween(a)).to({a:1},
1E3).onUpdate(function(c,d){b.title1.alpha=a.a}).start();(new MGE.Tweener.Tween(c)).to({a:1},1E3).delay(200).onUpdate(function(){b.title2.alpha=c.a}).start();var e={a:0},f=(new MGE.Tweener.Tween(e)).to({a:1},1E3).onUpdate(function(){b.skip.alpha=e.a});(new MGE.Tweener.Tween(d)).to({a:1},1E3).delay(400).onUpdate(function(){b.title3.alpha=d.a}).onComplete(function(){f.start()}).start()}};FE.Moves=function(b,a){this.game=b;this.layer=a;this.movesText=new MGE.BitmapText("",this.game.font);this.layer.addChild(this.movesText)};
FE.Moves.prototype._align=function(){this.movesText.x=this.game.width/2-this.movesText.textWidth/2;this.movesText.y=6};FE.Moves.prototype.setMoves=function(b){var a=this,c={a:1};(new MGE.Tweener.Tween(c)).to({a:0},300).repeat(1).yoyo(!0).onUpdate(function(){a.movesText.alpha=c.a}).onYoyo(function(){a.movesText.setText(b);a._align()}).start()};
FE.Elements=function(b,a,c){this.game=b;this.layer=a;MGE.DisplayObjectContainer.call(this);this.layer.addChild(this);this.textures=[MGE.TextureCache.fire,MGE.TextureCache.water,MGE.TextureCache.earth,MGE.TextureCache.air];this.init();this._pool=[];this._textPool=[];this._maxPool=30;this.initPool();this.createHitArea();this.selected={};this.lastSelected={col:-1,row:-1};this.comboCount=0;this.whosTurnItIs=c};FE.Elements.prototype=Object.create(MGE.DisplayObjectContainer.prototype);
FE.Elements.prototype.constructor=FE.Elements;FE.Elements.prototype.init=function(){this.removeAll();for(var b=0;b<this.game.grid.size.y;b++)for(var a=0;a<this.game.grid.size.x;a++)(new MGE.Sprite(this.textures[this.game.grid.getItem(b,a)].src)).applyParams({scaleX:2,scaleY:2,x:51*a+32,y:51*b+243}).addTo(this)};
FE.Elements.prototype.initPool=function(){this.poolContainer=new MGE.DisplayObjectContainer;this.addChild(this.poolContainer);this.textPoolContainer=new MGE.DisplayObjectContainer;this.addChild(this.textPoolContainer);this.comboPoolContainer=new MGE.DisplayObjectContainer;this.addChild(this.comboPoolContainer);for(var b=0;b<this._maxPool;b++){var a=(new MGE.Sprite(this.textures[0].src)).applyParams({visible:!1}).addTo(this.poolContainer);this._pool.push(a);a=new MGE.BitmapText("12345",this.game.smallFontGrey);
a.applyParams({visible:!1}).addTo(this.textPoolContainer);this._textPool.push(a)}a=new MGE.BitmapText("X COMBO",this.game.comboFont);a.applyParams({visible:!1}).addTo(this.comboPoolContainer)};FE.Elements.prototype.getFromPool=function(b){for(var a=0;a<this._maxPool;a++)if(!1===this[b][a].visible){this[b][a].visible=!0;break}return a>=this._maxPool?null:this[b][a]};FE.Elements.prototype.interactive=function(b){this.area.active=b};
FE.Elements.prototype.animateRemoved=function(b,a){for(var c in b){var d=this.getFromPool("_pool"),e=this.children[b[c].row*this.game.grid.size.x+b[c].col];e.visible=!1;null==d&&a&&a.call();d.applyParams({texture:e.texture,x:e.x,y:e.y,scaleX:e.scaleX,scaleY:e.scaleY});this.animateOneRemoved(d,c,null)}a&&a.call()};
FE.Elements.prototype.animateOneRemoved=function(b,a,c){var d=this,e={x:b.x,y:b.y,s:2},f={x:this.game.opponent.x+this.game.opponent.avatar.x,y:this.game.opponent.y+this.game.opponent.avatar.y,s:1};(new MGE.Tweener.Tween(e)).to(f,500).delay(100*a).onUpdate(function(){b.x=e.x;b.y=e.y;b.scaleX=e.s;b.scaleY=e.s}).onComplete(function(){setTimeout(function(){d.animateDamage(b,d.game.opponent);b.visible=!1},30);c&&c.call()}).start()};
FE.Elements.prototype.animateDamage=function(b,a,c){for(var d=0;d<this.textures.length&&b.texture.src!=this.textures[d].src;d++);var d=a.getDamage(d,a==this.game.opponent?this.game.player.properties.attack:this.game.opponent.properties.attack),e=this.getFromPool("_textPool");e.applyParams({x:b.x+30*Math.random()-15,y:b.y-30});e.setText("-"+d);this.animateOpponent(a);var f={y:e.y,a:1};b={y:e.y-50,a:0};(new MGE.Tweener.Tween(f)).to(b,1E3).onUpdate(function(){e.y=Math.floor(f.y);e.alpha=f.a}).onComplete(function(){setTimeout(function(){e.visible=
!1},30);c&&c.call()}).start()};FE.Elements.prototype.animateOpponent=function(b){if(!b.isDead){var a={s:4};(new MGE.Tweener.Tween(a)).to({s:4.3},45).repeat(1).yoyo(!0).onUpdate(function(){b.avatar.scaleX=b.avatar.scaleY=a.s}).start()}};
FE.Elements.prototype.checkMove=function(b,a){var c=[],d=[];this.game.player.moves--;0<=this.game.player.moves&&this.game.moves.setMoves(this.game.player.moves.toString());this.game.grid.isStreak(b.row,b.col)||this.game.grid.isStreak(a.row,a.col)?(this.interactive(!1),this.game.grid.isStreak(b.row,b.col)&&(c=this.game.grid.removeItems(b.row,b.col)),this.game.grid.isStreak(a.row,a.col)&&(d=this.game.grid.removeItems(a.row,a.col)),0<d.length&&(c=c.concat(d)),this.animateRemoved(c),this.applyGravity()):
this.checkMovesCount()};FE.Elements.prototype.applyGravity=function(){var b=this;this.falling=!0;var a=this.game.grid.applyGravity();this.fallDownSpritesAnimation(a,function(){b.reorderFallenSprites(a);0!=a.length?b.applyGravity():b.checkCombo(function(){setTimeout(function(){b.refill()},30)})})};FE.Elements.prototype.checkCombo=function(b){var a=this.game.grid.checkCombo();0!=a.count?(this.comboCount++,this.animateRemoved(a.removed,function(){setTimeout(function(){b&&b.call()},30)})):b&&b.call()};
FE.Elements.prototype.refill=function(b){b=this.game.grid.refillGrid();var a=this,c;for(c in b){var d=b[c].row*this.game.grid.size.x+b[c].col;this.children[d].texture=this.textures[this.game.grid.getItem(b[c].row,b[c].col)];this.children[d].visible=!0}0!=b.length?this.applyGravity():0<this.comboCount?this.showComboWords(this.comboCount,function(){a.comboCount=0;a.interactive(!0);a.checkMovesCount()}):(a.interactive(!0),this.checkMovesCount())};
FE.Elements.prototype.showComboWords=function(b,a){var c=this;this.animatingCombo?a&&a.call():(this.animatingCombo=!0,this.animateComboWord(b,function(){c.animatingCombo=!1;a&&a.call()}))};
FE.Elements.prototype.animateComboWord=function(b,a){var c=this.comboPoolContainer.children[0];c.setText(b+"X COMBO");c.visible=!0;c.x=this.game.width/2-c.textWidth/2;c.y=340;var d={y:480};(new MGE.Tweener.Tween(d)).to({y:190},3E3).onUpdate(function(){c.y=Math.floor(d.y)}).onComplete(function(){c.visible=!1;a&&a.call()}).start();var e={a:0};(new MGE.Tweener.Tween(e)).to({a:1},1500).repeat(1).yoyo(!0).onUpdate(function(){c.alpha=e.a}).start()};
FE.Elements.prototype.reorderFallenSprites=function(b){for(var a in b)this.children[b[a].row*this.game.grid.size.x+b[a].col].y-=51;this.resetSprites(b)};
FE.Elements.prototype.resetSprites=function(b){for(b=0;b<this.game.grid.size.y;b++)for(var a=0;a<this.game.grid.size.x;a++)-1!=this.game.grid.getItem(b,a)?(this.children[b*this.game.grid.size.x+a].visible=!0,this.children[b*this.game.grid.size.x+a].texture=this.textures[this.game.grid.getItem(b,a)]):(this.children[b*this.game.grid.size.x+a].visible=!1,this.children[b*this.game.grid.size.x+a].texture=this.textures[0])};
FE.Elements.prototype.fallDownSpritesAnimation=function(b,a){if(this.animating)console.log("fallDownSpritesAnimation still animating... return");else{var c=this,d=[],e={y:0};this.animating=!0;for(var f in b)d.push(this.children[b[f].row*this.game.grid.size.x+b[f].col].y);(new MGE.Tweener.Tween(e)).to({y:51},60).easing("Linear").onUpdate(function(){for(var a in b)c.children[b[a].row*c.game.grid.size.x+b[a].col].y=d[a]+e.y}).onComplete(function(){c.animating=!1;setTimeout(function(){for(var f in b)c.children[b[f].row*
c.game.grid.size.x+b[f].col].y=d[f]+e.y;a&&a.call()},5)}).start()}};FE.Elements.prototype.checkMovesCount=function(){this.game.player.isDead||this.game.opponent.isDead?(this.interactive(!1),this.gameOver()):0>=this.game.player.moves&&(this.interactive(!1),this.roundOver())};
FE.Elements.prototype.opponentAttack=function(){var b=this,a=this.getFromPool("_pool");a.applyParams({texture:this.textures[FE.TYPES[this.game.opponent.properties.type]],x:this.game.opponent.x+this.game.opponent.avatar.x,y:this.game.opponent.y+this.game.opponent.avatar.y,scaleX:2,scaleY:2});var c={s:2};(new MGE.Tweener.Tween(c)).to({s:4},500).onUpdate(function(){a.scaleX=c.s;a.scaleY=c.s}).start();var d={s:4};(new MGE.Tweener.Tween(d)).to({s:3},500).repeat(2).yoyo(!0).delay(500).onUpdate(function(){a.scaleX=
d.s;a.scaleY=d.s}).start();var e={s:4,x:a.x,y:a.y},f={s:2,x:this.game.player.x+this.game.player.avatar.x,y:this.game.player.y+this.game.player.avatar.y};(new MGE.Tweener.Tween(e)).to(f,200).delay(2E3).onUpdate(function(){a.scaleX=e.s;a.scaleY=e.s;a.x=e.x;a.y=e.y}).onComplete(function(){a.visible=!1;b.animateDamage(a,b.game.player);b.checkMovesCount()}).start()};
FE.Elements.prototype.roundOver=function(){console.log("round over");this.whosTurnItIs=!this.whosTurnItIs;1==this.whosTurnItIs?this.opponentAttack():(this.game.player.moves=this.game.player.defaultMoves,this.game.moves.setMoves(this.game.player.moves.toString()),this.interactive(!0))};
FE.Elements.prototype.gameOver=function(){var b=this;this.interactive(!1);this.game.overLayer.visible=!0;this.game.overLayer.area.active=!0;this.game.opponent.isDead?(FE.CURRENTENEMY++,this.game.overLayer.overText.setText("YOU WIN!"),this.game.overLayer.overText.applyParams({x:this.game.width/2-this.game.overLayer.overText.textWidth/2}),this.game.overLayer.overText2.setText("PREPARE FOR"),this.game.overLayer.overText2.applyParams({x:this.game.width/2-this.game.overLayer.overText2.textWidth/2}),this.game.overLayer.overText3.setText("NEXT ROUND"),
this.game.overLayer.overText3.applyParams({x:this.game.width/2-this.game.overLayer.overText3.textWidth/2}),this.game.overLayer.continueButton.setText("CONTINUE")):(this.game.overLayer.overText.setText("YOU LOSE!"),this.game.overLayer.overText.applyParams({x:this.game.width/2-this.game.overLayer.overText.textWidth/2}),this.game.overLayer.overText2.setText("BETTER LUCK"),this.game.overLayer.overText2.applyParams({x:this.game.width/2-this.game.overLayer.overText2.textWidth/2}),this.game.overLayer.overText3.setText("NEXT TIME!"),
this.game.overLayer.overText3.applyParams({x:this.game.width/2-this.game.overLayer.overText3.textWidth/2}),this.game.overLayer.continueButton.setText("RESTART"));FE.CURRENTENEMY+1>FE.OPPONENTS.length?(this.game.overLayer.continueButton.visible=!1,this.game.overLayer.overText.setText("GAME OVER"),this.game.overLayer.overText.applyParams({x:this.game.width/2-this.game.overLayer.overText.textWidth/2}),this.game.overLayer.overText2.setText("YOU DID IT!"),this.game.overLayer.overText2.applyParams({x:this.game.width/
2-this.game.overLayer.overText2.textWidth/2}),this.game.overLayer.overText3.setText("YOU SAVED LIVES"),this.game.overLayer.overText3.applyParams({x:this.game.width/2-this.game.overLayer.overText3.textWidth/2})):this.game.overLayer.area.onPointerDown=function(){b.game.player.isDead&&(FE.CURRENTENEMY=0);b.game.overLayer.area.active=!1;b.game.opponent.properties=FE.OPPONENTS[FE.CURRENTENEMY];b.game.opponent.reset();b.game.player.reset();b.game.overLayer.visible=!1;b.interactive(!0);b.game.moves.setMoves(b.game.player.moves.toString())};
console.log("game over")};
FE.Elements.prototype.doDecision=function(b){var a=this;this.selected.col==this.lastSelected.col&&this.selected.row==this.lastSelected.row?(this.highlight(this.selected,2.5,2),this.lastSelected.col=-1,this.lastSelected.row=-1):(a.tmp={col:a.lastSelected.col,row:a.lastSelected.row},this.highlight(this.selected,2,2.5,function(){setTimeout(function(){-1!==a.tmp.col&&-1!==a.tmp.row&&(a.game.grid.swap(a.selected,a.tmp),a.interactive(!1),a.game.grid.isStreak(a.selected.row,a.selected.col)&&a.game.grid.isStreak(a.tmp.row,
a.tmp.col)||setTimeout(function(){a.interactive(!0);a.checkMovesCount()},550),a.swap(a.selected,a.tmp,function(){setTimeout(function(){a.checkMove(a.selected,a.tmp);a.lastSelected.col=-1;a.lastSelected.row=-1},50)}))},50)}),a.lastSelected.col=a.selected.col,a.lastSelected.row=a.selected.row)};FE.Elements.prototype.createHitArea=function(){var b=this;this.area=new MGE.HitArea(7,218,306,255);this.area.onPointerDown=function(a){b.selected=b.determinePosition(a,this);b.doDecision()}};
FE.Elements.prototype.determinePosition=function(b,a){return{col:Math.floor((b.x-a.x)/51),row:Math.floor((b.y-a.y)/51)}};FE.Elements.prototype.highlight=function(b,a,c,d){var e={s:a};a={s:c};var f=this.children[b.row*this.game.grid.size.x+b.col];(new MGE.Tweener.Tween(e)).to(a,200).onUpdate(function(){f.scaleX=e.s;f.scaleY=e.s}).onComplete(function(){d&&d.call()}).start()};
FE.Elements.prototype.swap=function(b,a,c){var d=this.children[b.row*this.game.grid.size.x+b.col],e=this.getFromPool("_pool");e.applyParams({texture:d.texture,x:d.x,y:d.y,scaleX:d.scaleX,scaleY:d.scaleY});var f=this.children[a.row*this.game.grid.size.x+a.col],g=this.getFromPool("_pool");g.applyParams({texture:f.texture,x:f.x,y:f.y,scaleX:f.scaleX,scaleY:f.scaleY});d.applyParams({texture:f.texture,scaleX:2,scaleY:2,visible:!1});f.applyParams({texture:e.texture,scaleX:2,scaleY:2,visible:!1});var h=
{x1:e.x,y1:e.y,x2:g.x,y2:g.y,s:2.5};b={x1:g.x,y1:g.y,x2:e.x,y2:e.y,s:2};(new MGE.Tweener.Tween(h)).to(b,500).onUpdate(function(){e.x=h.x1;e.y=h.y1;e.scaleX=h.s;e.scaleY=h.s;g.x=h.x2;g.y=h.y2;g.scaleX=h.s;g.scaleY=h.s}).onComplete(function(){d.visible=!0;f.visible=!0;e.visible=!1;g.visible=!1;c&&c.call()}).start()};