// Generated by js_of_ocaml 3.7.0
(function(c){"use strict";var
aj=1000.,a2=" : flags Open_text and Open_binary are not compatible",a9="em",bh="black",a8="Sys_error",bg="Invalid_argument",aV=0xf0,D=2000.,bf=0x800,ai="class",am=2147483000.,ao="jsError",G=1024,be="End_of_file",m=0x80,bd="Failure",aU="Undefined_recursive_module",a7=" : flags Open_rdonly and Open_wronly are not compatible",a6="([^/]*)",bc="glitch",a5=512,a1="Stack_overflow",b="",ak="^",aS=250.,aT=0xe0,a4=" : file already exists",C=0x3f,aR=0xdfff,a0="Not_found",aQ="Assert_failure",p="/",aZ="done",Q="body",an=128,a$="Sys_blocked_io",ba="fd ",bb=0xdc00,a3="Out_of_memory",aY="Match_failure",h=248,al="index out of bounds",ah=500.,aX="static/",a_="Division_by_zero",aW=252,P="tr";function
av(d,c,a){var
e=String.fromCharCode;if(c==0&&a<=4096&&a==d.length)return e.apply(null,d);var
f=b;for(;0<a;c+=G,a-=G)f+=e.apply(null,d.slice(c,c+Math.min(a,G)));return f}function
S(b){if(c.Uint8Array)var
d=new(c.Uint8Array)(b.l);else
var
d=new
Array(b.l);var
f=b.c,e=f.length,a=0;for(;a<e;a++)d[a]=f.charCodeAt(a);for(e=b.l;a<e;a++)d[a]=0;b.c=d;b.t=4;return d}function
R(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?av(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?av(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)S(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
E(a){return a}function
ap(a,b,c,d,e){R(E(a),b,c,d,e);return 0}function
c0(b,a){throw[0,b,a]}function
bw(c,a){if(c==0)return b;if(a.repeat)return a.repeat(c);var
e=b,d=0;for(;;){if(c&1)e+=a;c>>=1;if(c==0)return e;a+=a;d++;if(d==9)a.slice(0,1)}}function
T(a){if(a.t==2)a.c+=bw(a.l-a.c.length,"\0");else
a.c=av(a.c,0,a.c.length);a.t=0}function
bz(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
aw(f){for(var
k=b,d=b,h,g,i,a,c=0,j=f.length;c<j;c++){g=f.charCodeAt(c);if(g<m){for(var
e=c+1;e<j&&(g=f.charCodeAt(e))<m;e++);if(e-c>a5){d.substr(0,1);k+=d;d=b;k+=f.slice(c,e)}else
d+=f.slice(c,e);if(e==j)break;c=e}a=1;if(++c<j&&((i=f.charCodeAt(c))&-64)==an){h=i+(g<<6);if(g<aT){a=h-0x3080;if(a<m)a=1}else{a=2;if(++c<j&&((i=f.charCodeAt(c))&-64)==an){h=i+(h<<6);if(g<aV){a=h-0xe2080;if(a<bf||a>=0xd7ff&&a<0xe000)a=2}else{a=3;if(++c<j&&((i=f.charCodeAt(c))&-64)==an&&g<0xf5){a=i-0x3c82080+(h<<6);if(a<0x10000||a>0x10ffff)a=3}}}}}if(a<4){c-=a;d+="\ufffd"}else
if(a>0xffff)d+=String.fromCharCode(0xd7c0+(a>>10),bb+(a&0x3FF));else
d+=String.fromCharCode(a);if(d.length>G){d.substr(0,1);k+=d;d=b}}return k+d}function
q(c,a,b){this.t=c;this.c=a;this.l=b}q.prototype.toString=function(){switch(this.t){case
9:return this.c;default:T(this);case
0:if(bz(this.c)){this.t=9;return this.c}this.t=8;case
8:return this.c}};q.prototype.toUtf16=function(){var
a=this.toString();if(this.t==9)return a;return aw(a)};q.prototype.slice=function(){var
a=this.t==4?this.c.slice():this.c;return new
q(this.t,a,this.l)};function
bl(a){return new
q(0,a,a.length)}function
a(a){return bl(a)}function
as(c,b){c0(c,a(b))}var
e=[0];function
U(a){as(e.Invalid_argument,a)}function
bj(){U(al)}function
aq(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
bk(b,a){if(a>>>0>=b.l)bj();return aq(b,a)}function
bm(a,c,b){b&=0xff;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}S(a)}a.c[c]=b;return 0}function
z(c,a){if(c.fun)return z(c.fun,a);if(typeof
c!=="function")return c;var
b=c.length|0;if(b===0)return c.apply(null,a);var
e=a.length|0,d=b-e|0;if(d==0)return c.apply(null,a);else
if(d<0)return z(c.apply(null,a.slice(0,b)),a.slice(b));else
return function(){var
e=arguments.length==0?1:arguments.length,d=new
Array(a.length+e);for(var
b=0;b<a.length;b++)d[b]=a[b];for(var
b=0;b<arguments.length;b++)d[a.length+b]=arguments[b];return z(c,d)}}function
cH(){U(al)}function
bn(a,b){if(b>>>0>=a.length-1)cH();return a}function
r(a){if(a<0)U("Bytes.create");return new
q(a?2:9,b,a)}function
cP(a,d,c,e){if(c>0)if(d==0&&(c>=a.l||a.t==2&&c>=a.c.length))if(e==0){a.c=b;a.t=2}else{a.c=bw(c,String.fromCharCode(e));a.t=c==a.l?0:2}else{if(a.t!=4)S(a);for(c+=d;d<c;d++)a.c[d]=e}return 0}var
cX=0;function
I(){return cX++}function
cO(a){as(e.Failure,a)}function
s(a){return a.toUtf16()}if(c.process&&c.process.cwd)var
H=c.process.cwd().replace(/\\/g,p);else
var
H="/static";if(H.slice(-1)!==p)H+=p;function
cR(a){a=s(a);if(a.charCodeAt(0)!=47)a=H+a;var
e=a.split(p),c=[];for(var
d=0;d<e.length;d++)switch(e[d]){case"..":if(c.length>1)c.pop();break;case".":break;case"":if(c.length==0)c.push(b);break;default:c.push(e[d]);break}c.orig=a;return c}function
ar(a){return a
instanceof
q}function
bp(a){return ar(a)}function
cL(a){return new
q(4,a,a.length)}function
c5(f){for(var
g=b,c=g,a,i,d=0,h=f.length;d<h;d++){a=f.charCodeAt(d);if(a<m){for(var
e=d+1;e<h&&(a=f.charCodeAt(e))<m;e++);if(e-d>a5){c.substr(0,1);g+=c;c=b;g+=f.slice(d,e)}else
c+=f.slice(d,e);if(e==h)break;d=e}if(a<bf){c+=String.fromCharCode(0xc0|a>>6);c+=String.fromCharCode(m|a&C)}else
if(a<0xd800||a>=aR)c+=String.fromCharCode(aT|a>>12,m|a>>6&C,m|a&C);else
if(a>=0xdbff||d+1==h||(i=f.charCodeAt(d+1))<bb||i>aR)c+="\xef\xbf\xbd";else{d++;a=(a<<10)+i-0x35fdc00;c+=String.fromCharCode(aV|a>>18,m|a>>12&C,m|a>>6&C,m|a&C)}if(c.length>G){c.substr(0,1);g+=c;c=b}}return g+c}function
cM(a){var
b=9;if(!bz(a))b=8,a=c5(a);return new
q(b,a,a.length)}function
A(a){return cM(a)}function
d(a){as(e.Sys_error,a)}function
V(a){if((a.t&6)!=0)T(a);return a.c}function
cZ(a){a=V(a);d(a+": No such file or directory")}function
W(a){return a.l}function
bi(){}function
g(a){this.data=a}g.prototype=new
bi();g.prototype.truncate=function(a){var
b=this.data;this.data=r(a|0);R(b,0,this.data,0,a)};g.prototype.length=function(){return W(this.data)};g.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=r(b+a),f=this.data;this.data=e;R(f,0,this.data,0,c)}ap(d,g,this.data,b,a);return 0};g.prototype.read=function(c,a,d,b){var
e=this.length();R(this.data,c,a,d,b);return 0};g.prototype.read_one=function(a){return bk(this.data,a)};g.prototype.close=function(){};g.prototype.constructor=g;function
j(b,a){this.content={};this.root=b;this.lookupFun=a}j.prototype.nm=function(a){return this.root+a};j.prototype.lookup=function(b){if(!this.content[b]&&this.lookupFun){var
c=this.lookupFun(a(this.root),a(b));if(c!==0)this.content[b]=new
g(E(c[1]))}};j.prototype.exists=function(a){if(a==b)return 1;var
d=a+p,e=new
RegExp(ak+d);for(var
c
in
this.content)if(c.match(e))return 1;this.lookup(a);return this.content[a]?1:0};j.prototype.readdir=function(d){var
g=d==b?b:d+p,h=new
RegExp(ak+g+a6),e={},c=[];for(var
f
in
this.content){var
a=f.match(h);if(a&&!e[a[1]]){e[a[1]]=true;c.push(a[1])}}return c};j.prototype.is_dir=function(a){var
e=a==b?b:a+p,f=new
RegExp(ak+e+a6),g=[];for(var
d
in
this.content){var
c=d.match(f);if(c)return 1}return 0};j.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};j.prototype.open=function(a,b){if(b.rdonly&&b.wronly)d(this.nm(a)+a7);if(b.text&&b.binary)d(this.nm(a)+a2);this.lookup(a);if(this.content[a]){if(this.is_dir(a))d(this.nm(a)+" : is a directory");if(b.create&&b.excl)d(this.nm(a)+a4);var
c=this.content[a];if(b.truncate)c.truncate();return c}else
if(b.create){this.content[a]=new
g(r(0));return this.content[a]}else
cZ(this.nm(a))};j.prototype.register=function(b,a){if(this.content[b])d(this.nm(b)+a4);if(ar(a))this.content[b]=new
g(a);if(bp(a))this.content[b]=new
g(E(a));else
if(a
instanceof
Array)this.content[b]=new
g(cL(a));else
if(typeof
a==="string")this.content[b]=new
g(bl(a));else
if(a.toString){var
c=E(A(a.toString()));this.content[b]=new
g(c)}else
d(this.nm(b)+" : registering file with invalid content type")};j.prototype.constructor=j;function
u(a){return W(a)}function
X(b,a){return aq(b,a)}function
cJ(d){var
c=u(d),b=new
Array(c),a=0;for(;a<c;a++)b[a]=X(d,a);return b}function
cI(a){if(a.t!=4)S(a);return a.c}function
cN(b,a,c){if(a>>>0>=b.l)bj();return bm(b,a,c)}function
o(a){this.fs=require("fs");this.fd=a}o.prototype=new
bi();o.prototype.truncate=function(a){try{this.fs.ftruncateSync(this.fd,a|0)}catch(a){d(a.toString())}};o.prototype.length=function(){try{return this.fs.fstatSync(this.fd).size}catch(a){d(a.toString())}};o.prototype.write=function(h,b,e,g){var
a=cJ(b);if(!(a
instanceof
c.Uint8Array))a=new(c.Uint8Array)(a);var
f=c.Buffer.from(a);try{this.fs.writeSync(this.fd,f,e,g,h)}catch(a){d(a.toString())}return 0};o.prototype.read=function(i,f,e,h){var
a=cI(f);if(!(a
instanceof
c.Uint8Array))a=new(c.Uint8Array)(a);var
g=c.Buffer.from(a);try{this.fs.readSync(this.fd,g,e,h,i)}catch(a){d(a.toString())}for(var
b=0;b<h;b++)cN(f,e+b,g[e+b]);return 0};o.prototype.read_one=function(e){var
b=new(c.Uint8Array)(1),a=c.Buffer.from(b);try{this.fs.readSync(this.fd,a,0,1,e)}catch(a){d(a.toString())}return a[0]};o.prototype.close=function(){try{this.fs.closeSync(this.fd)}catch(a){d(a.toString())}};o.prototype.constructor=o;function
n(a){this.fs=require("fs");this.root=a}n.prototype.nm=function(a){return this.root+a};n.prototype.exists=function(a){try{return this.fs.existsSync(this.nm(a))?1:0}catch(a){d(a.toString())}};n.prototype.readdir=function(a){try{return this.fs.readdirSync(this.nm(a))}catch(a){d(a.toString())}};n.prototype.is_dir=function(a){try{return this.fs.statSync(this.nm(a)).isDirectory()?1:0}catch(a){d(a.toString())}};n.prototype.unlink=function(a){try{var
b=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a))}catch(a){d(a.toString())}return b};n.prototype.open=function(g,c){var
a=require("constants"),b=0;for(var
f
in
c)switch(f){case"rdonly":b|=a.O_RDONLY;break;case"wronly":b|=a.O_WRONLY;break;case"append":b|=a.O_WRONLY|a.O_APPEND;break;case"create":b|=a.O_CREAT;break;case"truncate":b|=a.O_TRUNC;break;case"excl":b|=a.O_EXCL;break;case"binary":b|=a.O_BINARY;break;case"text":b|=a.O_TEXT;break;case"nonblock":b|=a.O_NONBLOCK;break}try{var
e=this.fs.openSync(this.nm(g),b);return new
o(e)}catch(a){d(a.toString())}};n.prototype.rename=function(b,a){try{this.fs.renameSync(this.nm(b),this.nm(a))}catch(a){d(a.toString())}};n.prototype.constructor=n;var
F=H.match(/[^\/]*\//)[0];function
c6(){return typeof
c.process!=="undefined"&&typeof
c.process.versions!=="undefined"&&typeof
c.process.versions.node!=="undefined"&&c.process.platform!=="browser"}var
J=[];if(c6())J.push({path:F,device:new
n(F)});else
J.push({path:F,device:new
j(F)});J.push({path:F+aX,device:new
j(F+aX)});function
bA(b){var
f=cR(b),b=f.join(p),e=b+p,c;for(var
d=0;d<J.length;d++){var
a=J[d];if(e.search(a.path)==0&&(!c||c.path.length<a.path.length))c={path:a.path,device:a.device,rest:b.substring(a.path.length,b.length)}}return c}function
bo(c,b){var
c=typeof
c=="string"?a(c):c,b=typeof
b=="string"?a(b):b,d=bA(c);if(!d.device.register)cO("cannot register file");d.device.register(d.rest,b);return 0}function
cQ(){var
b=c.caml_fs_tmp;if(b)for(var
a=0;a<b.length;a++)bo(b[a].name,b[a].content);c.caml_create_file=bo;c.caml_fs_tmp=[];return 0}function
bq(d){return function(){var
b=arguments.length;if(b>0){var
c=new
Array(b);for(var
a=0;a<b;a++)c[a]=arguments[a];return z(d,c)}else
return z(d,[undefined])}}var
t=new
Array();function
cS(f){var
a=t[f];if(!a.opened)d("Cannot flush a closed channel");if(!a.buffer||a.buffer==b)return 0;if(a.fd&&e.fds[a.fd]&&e.fds[a.fd].output){var
c=e.fds[a.fd].output;switch(c.length){case
2:c(f,a.buffer);break;default:c(a.buffer)}}a.buffer=b;return 0}function
bv(e,f){var
b=t[e],d=a(f),c=u(d);b.file.write(b.offset,d,0,c);b.offset+=c;return 0}function
c7(a){var
a=aw(a),b=c;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
d=b.console;d&&d.error&&d.error(a)}}function
c8(a){var
a=aw(a),b=c;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
d=b.console;d&&d.log&&d.log(a)}}function
Y(c,f,d,a){if(e.fds===undefined)e.fds=new
Array();a=a?a:{};var
b={};b.file=d;b.offset=a.append?d.length():0;b.flags=a;b.output=f;e.fds[c]=b;if(!e.fd_last_idx||c>e.fd_last_idx)e.fd_last_idx=c;return c}function
c9(c,b,i){var
a={};while(b){switch(b[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}b=b[2]}if(a.rdonly&&a.wronly)d(V(c)+a7);if(a.text&&a.binary)d(V(c)+a2);var
f=bA(c),g=f.device.open(f.rest,a),h=e.fd_last_idx?e.fd_last_idx:0;return Y(h+1,bv,g,a)}Y(0,bv,new
g(r(0)));Y(1,c8,new
g(r(0)));Y(2,c7,new
g(r(0)));function
cT(c){var
b=e.fds[c];if(b.flags.wronly)d(ba+c+" is writeonly");var
a={file:b.file,offset:b.offset,fd:c,opened:true,out:false,refill:null};t[a.fd]=a;return a.fd}function
br(f){var
c=e.fds[f];if(c.flags.rdonly)d(ba+f+" is readonly");var
a={file:c.file,offset:c.offset,fd:f,opened:true,out:true,buffer:b};t[a.fd]=a;return a.fd}function
cU(){var
b=0;for(var
a=0;a<t.length;a++)if(t[a]&&t[a].opened&&t[a].out)b=[0,t[a].fd,b];return b}function
cY(a){throw a}function
c1(){cY(e.Division_by_zero)}function
cV(b,a){if(a==0)c1();return b%a}function
cW(a){if(a
instanceof
Array&&a[0]==a[0]>>>0)return a[0];else
if(ar(a))return aW;else
if(bp(a))return aW;else
if(a
instanceof
Function||typeof
a=="function")return 247;else
if(a&&a.caml_custom)return 255;else
return 1000}function
k(b,d,a){if(a&&c.toplevelReloc)b=c.toplevelReloc(a);e[b+1]=d;if(a)e[a]=d}var
bt={};function
c2(a,b){bt[V(a)]=b;return 0}function
cK(a,b){if(a===b)return 1;a.t&6&&T(a);b.t&6&&T(b);return a.c==b.c?1:0}function
bx(a,b){return cK(a,b)}function
c3(){U(al)}function
at(b,a){if(a>>>0>=u(b))c3();return X(b,a)}function
au(a){return a}function
c4(){return[0,a("js_of_ocaml")]}function
bu(a){return a}function
bs(a){return bt[a]}function
by(a){if(a
instanceof
Array)return a;if(c.RangeError&&a
instanceof
c.RangeError&&a.message&&a.message.match(/maximum call stack/i))return bu(e.Stack_overflow);if(c.InternalError&&a
instanceof
c.InternalError&&a.message&&a.message.match(/too much recursion/i))return bu(e.Stack_overflow);if(a
instanceof
c.Error&&bs(ao))return[0,bs(ao),a];return[0,e.Failure,A(String(a))]}function
i(a,b){return a.length==1?a(b):z(a,[b])}function
cG(a,b,c){return a.length==2?a(b,c):z(a,[b,c])}cQ();var
az=[h,a(a8),-2],ax=[h,a(bg),-4],Z=[h,a(a0),-7];k(11,[h,a(aU),-12],aU);k(10,[h,a(aQ),-11],aQ);k(9,[h,a(a$),-10],a$);k(8,[h,a(a1),-9],a1);k(7,[h,a(aY),-8],aY);k(6,Z,a0);k(5,[h,a(a_),-6],a_);k(4,[h,a(be),-5],be);k(3,ax,bg);k(2,[h,a(bd),-3],bd);k(1,az,a8);k(0,[h,a(a3),-1],a3);var
bC=a("option is None"),bF=a("String.contains_from / Bytes.contains_from"),bJ=a("Js_of_ocaml__Js.Error"),cF=a("ltrs"),cE=a("ch"),cC=a("th"),cD=a(Q),cA=a('<span class="box c">_<\/span>'),cz=a('<span class="box"> <\/span>'),cB=a(b),cw=a("vanish"),cx=a("not"),cs=a(aZ),ct=a(Q),co=a("th2"),cn=a("th2 off"),cp=a(Q),cj=a("rot drop"),ci=a("rot"),ck=a("all"),ce=a(bc),cd=a("burn"),b$=a(bc),ca=a(a9),cb=a("s; --dist: "),cc=a("--del: "),b_=a("boom"),cf=a("y"),b5=a(a9),b6=a("--d: "),b7=a("rev"),b1=a(P),b2=a("fi"),bZ=a(P),b0=a("wi"),bX=a(P),bY=a("ea"),bV=a(P),bW=a("wa"),bR=a(aZ),bQ=a(bh),bS=a(Q),bN=a("counter"),bM=a("pick"),bL=a("puzzle"),bO=a("Thanks for playing!"),bT=a("That's all Folks!"),b3=a("water earth wind fire"),b8=a("desrever"),cg=a("It is gilchtyd"),cl=a("Everything is lost"),cq=a("Turn it off and on again"),cu=a("Bring me back to life"),cy=a("Theme not found");function
ay(a){throw[0,ax,a]}I(0);function
v(d,c){var
a=u(d),e=u(c),b=r(a+e|0);ap(d,0,b,0,a);ap(c,0,b,a,e);return au(b)}cT(0);br(1);br(2);function
aA(b,c,g){var
a=i(c,0);if(a){var
d=a[2],e=a[1],f=function(a){return aA(b,d,a)};return[0,i(b,e),f]}return 0}function
K(a){if(65<=a&&!(90<a))return a+32|0;return a}I(0);typeof
c4(0)==="number";function
bD(e,d,c,b){var
a=c;for(;;){if(d<=a)throw Z;if(X(e,a)===b)return a;var
a=a+1|0;continue}}function
bE(b,a,d){var
c=u(b);if(0<=a&&!(c<a))try{bD(b,c,a,d);var
e=1;return e}catch(a){a=by(a);if(a===Z)return 0;throw a}return ay(bF)}I(0);var
aB=[0,0];function
aC(a){aB[1]=[0,a,aB[1]];return 0}var
B=c,w=null,_=undefined;function
$(a,c){var
b=1-(a==w?1:0);return b?i(c,a):b}function
L(a,c,b){return a==w?i(c,0):i(b,a)}var
aD=true,bI=B.Array,aE=[h,bJ,I(0)],aa=[0,aE,{}],bH=false,bG=cW(aa)===h?aa:aa[1];c2(a(ao),bG);(function(a){throw a});aC(function(a){return a[1]===aE?[0,A(a[2].toString())]:0});aC(function(a){return a
instanceof
bI?0:[0,A(a.toString())]});function
ab(c){return function(a){if(1-(a==w?1:0)){var
d=i(c,a);if(1-(d|0))a.preventDefault();return d}var
e=event,b=i(c,e);if(1-(b|0))e.returnValue=b;return b}}var
ac=B.document;I(0);var
aF=B.HTMLElement,aG=aF===_?function(a){return a.innerHTML===_?w:a}:function(a){return a
instanceof
aF?a:w},bK=am;function
aH(a){return a}function
aI(a){return b}function
aJ(e,d){var
a=A(e),f=0,b=1===u(a)?at(a,0):f,c=b!==0?1:0;return c?i(d,b):c}function
ad(b){var
a=r(1);cP(a,0,1,b);return s(au(a))}function
M(d){function
b(b){var
c=aG(b);function
a(a){return[0,a]}return L(c,function(a){return 0},a)}function
c(a){return 0}var
a=L(ac.getElementById(s(d)),c,b);return a?a[1]:ay(bC)}function
x(b,a){return i(a,M(b))}function
N(b,a){return $(ac.querySelector(s(b)),a)}function
y(b,a){return b.setAttribute(ai,s(a))}function
l(a,d){var
c=a.getAttribute(ai),e=c==w?b:c;return a.setAttribute(ai,e.concat(" ",s(d)))}function
aK(b,a){return b.setAttribute("style",s(a))}function
ae(d,c,b){var
a=d.childNodes.item(c),e=a==w?w:aG(a);return $(e,b)}function
af(b,d){var
c=b.childNodes.length-1|0,e=0;if(!(c<0)){var
a=e;for(;;){ae(b,a,i(d,a));var
f=a+1|0;if(c!==a){var
a=f;continue}break}}return 0}function
f(a,g){var
e=[0,0];function
c(a,h){if(am<a)var
b=a-am,d=bK;else
var
b=0.,d=a;var
f=b==0.?g:function(a){return c(b,a)};e[1]=[0,B.setTimeout(bq(f),d)];return 0}c(a,0);return 0}function
aL(a){return f(a[1],a[2])}function
O(a,b){function
c(c){i(a[2],0);return aL(b)}return[0,a[1],c]}var
bP=[0,bO,function(b,a){return 0}],bU=[0,bT,function(a,b){return N(bS,function(a){return f(aj,function(c){l(a,bQ);return f(D,function(c){l(a,bR);return f(5000.,b)})})})}],b4=[0,b3,function(b,a){b[6].innerHTML='<span id="wa"><span class="box c">w<\/span><span class="box c">a<\/span><span class="box c">t<\/span><span class="box c">e<\/span><span class="box c">r<\/span><\/span><span class="box"> <\/span><span id="ea"><span class="box c">e<\/span><span class="box c">a<\/span><span class="box c">r<\/span><span class="box c">t<\/span><span class="box c">h<\/span><\/span><span class="box"> <\/span><span id="wi"><span class="box c">w<\/span><span class="box c">i<\/span><span class="box c">n<\/span><span class="box c">d<\/span><\/span><span class="box"> <\/span><span id="fi"><span class="box c">f<\/span><span class="box c">i<\/span><span class="box c">r<\/span><span class="box c">e<\/span><\/span>';f(aj,function(a){return x(bW,function(a){return l(a,bV)})});f(D,function(a){return x(bY,function(a){return l(a,bX)})});f(3000.,function(a){return x(b0,function(a){return l(a,bZ)})});f(4000.,function(a){return x(b2,function(a){return l(a,b1)})});return f(6000.,a)}],b9=[0,b8,function(c,d){function
e(d,c){return aK(c,v(b6,v(a(b+((3.5-d)*2.|0)),b5)))}af(c[6],e);l(c[6],b7);return f(5500.,d)}],ch=[0,cg,function(c,d){c[6].innerHTML='<span class="box c">I<\/span><span class="box c">t<\/span><span class="box"> <\/span><span class="box c">i<\/span><span class="box c">s<\/span><span class="box"> <\/span><span class="box c">g<\/span><span class="box c">i<\/span><span class="box c">l<\/span><span class="box c">c<\/span><span class="box c">h<\/span><span class="box c">t<\/span><span class="box c" id="y">y<\/span><span class="box c">d<\/span>';return x(cf,function(e){var
f=[0,D,d],g=O([0,D,function(a){return l(c[6],b_)}],f),h=O([0,ah,function(e){function
d(e,d){var
c=e-12|0,f=0<=c?c:-c|0;l(d,b$);return aK(d,v(cc,v(a(b+f),v(cb,v(a(b+((e-7.5)*2.|0)),ca)))))}return af(c[6],d)}],g),i=O([0,600.,function(a){return y(c[6],cd)}],h);return aL(O([0,400.,function(a){return l(e,ce)}],i))})}],cm=[0,cl,function(a,b){a[6].innerHTML='<span id="all"><span class="box c">E<\/span><span class="box c">v<\/span><span class="box c">e<\/span><span class="box c">r<\/span><span class="box c">y<\/span><span class="box c">t<\/span><span class="box c">h<\/span><span class="box c">i<\/span><span class="box c">n<\/span><span class="box c">g<\/span><span class="box"> <\/span><span class="box c">i<\/span><span class="box c">s<\/span><span class="box"> <\/span><\/span><span class="box c">l<\/span><span class="box c">o<\/span><span class="box c">s<\/span><span class="box c">t<\/span>';return x(ck,function(a){f(ah,function(b){return y(a,ci)});f(1550.,function(b){return y(a,cj)});return f(D,b)})}],cr=[0,cq,function(a,b){return N(cp,function(a){f(ah,function(b){return y(a,cn)});f(D,function(b){return y(a,co)});return f(3500.,b)})}],cv=[0,cu,function(b,a){return N(ct,function(b){l(b,cs);return f(1250.,a)})}],ag=[0,[0,cy,function(b,a){b[6].innerHTML='<span class="box c">T<\/span><span class="box c">h<\/span><span class="box c">e<\/span><span class="box c">m<\/span><span class="box c">e<\/span><span id="not"><span class="box"> <\/span><span class="box c">n<\/span><span class="box c">o<\/span><span class="box c">t<\/span><\/span><span class="box"> <\/span><span class="box c">f<\/span><span class="box c">o<\/span><span class="box c">u<\/span><span class="box c">n<\/span><span class="box c">d<\/span>';return x(cx,function(b){f(aS,function(a){return y(b,cw)});return f(1500.,a)})}],cv,cr,cm,ch,b9,b4,bU,bP];function
aM(a){return(ag.length-1-1|0)===a?1:0}function
aN(c){N(cD,function(d){return y(d,v(cC,a(b+c[1])))});var
n=c[4],h=E(n);function
m(a){return 32===a?cz:cA}function
g(a,d){if(a===W(h))return 0;var
b=bk(h,a),c=a+1|0;return[0,b,function(a){return g(c,a)}]}var
k=0;function
l(a){return g(k,a)}var
d=cB;function
f(a){return aA(m,l,a)}for(;;){var
e=i(f,0);if(e){var
j=e[2],d=v(d,e[1]),f=j;continue}c[6].innerHTML=s(d);return c[7].innerHTML=b}}function
aO(b,a){b[2]=a;return 0}function
aP(c,h){if(c[2]){var
q=K(h),t=function(a,d){var
b=K(at(c[4],a))===q?1:0,e=b?d.innerHTML=ad(at(c[4],a)):b;return e};af(c[6],t);if(1-aM(c[1])){var
g=E(c[4]),e=W(g);if(0===e)var
k=g;else{var
i=r(e),j=e-1|0,m=0;if(!(j<0)){var
d=m;for(;;){bm(i,d,K(aq(g,d)));var
n=d+1|0;if(j!==d){var
d=n;continue}break}}var
k=i}var
o=au(k);if(1-bE(o,0,K(h)))c[3]=c[3]+1|0}}var
w=c[7];w.innerHTML=ad(h);c[8].innerHTML=s(a(b+c[3]));var
p=L(c[6].textContent,aI,aH),v=c[4],l=bx(A(p),v);if(l){aO(c,0);var
x=function(o){aO(c,1);var
b=c[1]+1|0,h=bn(ag,b)[1+b];c[1]=b;c[4]=h[1];c[5]=h[2];aN(c);var
i=aM(c[1]);if(i){var
e=c[4],d=u(e)-1|0,j=0;if(!(d<0)){var
a=j;for(;;){var
k=X(e,a),m=function(b){return function(a){return a.innerHTML=ad(b)}}(k);ae(c[6],a,m);var
l=a+1|0;if(d!==a){var
a=l;continue}break}}var
g=[0,1],n=u(c[4]);B.setInterval(bq(function(d){g[1]++;var
a=cV((3*g[1]|0)%19|0,n);function
b(a){f(aS,function(b){return a.style.color=bh});return f(aj,function(b){return a.style.color="transparent"})}return ae(c[6],a,b)}),100.);return 0}return i};return cG(c[5],c,x)}return l}B.onload=ab(function(g){var
d=M(bL),e=M(bM),f=M(bN),c=bn(ag,0)[1],a=[0,0,1,0,c[1],c[2],d,e,f];aN(a);ac.onkeydown=ab(function(e){var
c=e.key,d=c===_?b:c;aJ(d,function(b){return aP(a,b)});return aD});x(cF,function(b){return b.onclick=ab(function(c){function
b(b){var
c=bx(A(b.className),cE);if(c){var
d=L(b.textContent,aI,aH);return aJ(d,function(b){return aP(a,b)})}return c}$(c.target,b);return aD})});return bH});function
bB(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{cS(d)}catch(a){a=by(a);if(a[1]!==az)throw a;var
e=a}var
a=c;continue}return 0}}bB(cU(0));return}(function(){return this}()));
